// Code generated by "kmipenums "; DO NOT EDIT.

package kmip

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strings"
)

// Tag
// 9.1.3.1
type Tag uint32

const (
	TagActivationDate                        Tag = 0x420001
	TagAlternativeName                       Tag = 0x4200bf
	TagAlternativeNameType                   Tag = 0x4200c1
	TagAlternativeNameValue                  Tag = 0x4200c0
	TagAlwaysSensitive                       Tag = 0x420121
	TagApplicationData                       Tag = 0x420002
	TagApplicationNamespace                  Tag = 0x420003
	TagApplicationSpecificInformation        Tag = 0x420004
	TagArchiveDate                           Tag = 0x420005
	TagAsynchronousCapability                Tag = 0x4200f0
	TagAsynchronousCorrelationValue          Tag = 0x420006
	TagAsynchronousIndicator                 Tag = 0x420007
	TagAttestationAssertion                  Tag = 0x4200cc
	TagAttestationCapability                 Tag = 0x4200f1
	TagAttestationCapableIndicator           Tag = 0x4200d3
	TagAttestationMeasurement                Tag = 0x4200cb
	TagAttestationType                       Tag = 0x4200c7
	TagAttribute                             Tag = 0x420008
	TagAttributeIndex                        Tag = 0x420009
	TagAttributeName                         Tag = 0x42000a
	TagAttributeValue                        Tag = 0x42000b
	TagAuthenticatedEncryptionAdditionalData Tag = 0x4200fe
	TagAuthenticatedEncryptionTag            Tag = 0x4200ff
	TagAuthentication                        Tag = 0x42000c
	TagBatchContinueCapability               Tag = 0x4200fa
	TagBatchCount                            Tag = 0x42000d
	TagBatchErrorContinuationOption          Tag = 0x42000e
	TagBatchItem                             Tag = 0x42000f
	TagBatchOrderOption                      Tag = 0x420010
	TagBatchUndoCapability                   Tag = 0x4200f9
	TagBlockCipherMode                       Tag = 0x420011
	TagCRTCoefficient                        Tag = 0x420027
	TagCancellationResult                    Tag = 0x420012
	TagCapabilityInformation                 Tag = 0x4200f7
	TagCertificate                           Tag = 0x420013
	TagCertificateIdentifier                 Tag = 0x420014
	TagCertificateIssuer                     Tag = 0x420015
	TagCertificateIssuerAlternativeName      Tag = 0x420016
	TagCertificateIssuerC                    Tag = 0x420118
	TagCertificateIssuerCN                   Tag = 0x420114
	TagCertificateIssuerDC                   Tag = 0x42011e
	TagCertificateIssuerDNQualifier          Tag = 0x42011f
	TagCertificateIssuerDistinguishedName    Tag = 0x420017
	TagCertificateIssuerEmail                Tag = 0x420117
	TagCertificateIssuerL                    Tag = 0x42011a
	TagCertificateIssuerO                    Tag = 0x420115
	TagCertificateIssuerOU                   Tag = 0x420116
	TagCertificateIssuerST                   Tag = 0x420119
	TagCertificateIssuerSerialNumber         Tag = 0x42011c
	TagCertificateIssuerTitle                Tag = 0x42011d
	TagCertificateIssuerUID                  Tag = 0x42011b
	TagCertificateLength                     Tag = 0x4200ad
	TagCertificateRequest                    Tag = 0x420018
	TagCertificateRequestType                Tag = 0x420019
	TagCertificateSerialNumber               Tag = 0x4200af
	TagCertificateSubject                    Tag = 0x42001a
	TagCertificateSubjectAlternativeName     Tag = 0x42001b
	TagCertificateSubjectC                   Tag = 0x42010c
	TagCertificateSubjectCN                  Tag = 0x420108
	TagCertificateSubjectDC                  Tag = 0x420112
	TagCertificateSubjectDNQualifier         Tag = 0x420113
	TagCertificateSubjectDistinguishedName   Tag = 0x42001c
	TagCertificateSubjectEmail               Tag = 0x42010b
	TagCertificateSubjectL                   Tag = 0x42010e
	TagCertificateSubjectO                   Tag = 0x420109
	TagCertificateSubjectOU                  Tag = 0x42010a
	TagCertificateSubjectST                  Tag = 0x42010d
	TagCertificateSubjectSerialNumber        Tag = 0x420110
	TagCertificateSubjectTitle               Tag = 0x420111
	TagCertificateSubjectUID                 Tag = 0x42010f
	TagCertificateType                       Tag = 0x42001d
	TagCertificateValue                      Tag = 0x42001e
	TagClientCorrelationValue                Tag = 0x420105
	TagClientRegistrationMethod              Tag = 0x4200f6
	TagComment                               Tag = 0x4200fd
	TagCommonTemplateAttribute               Tag = 0x42001f
	TagCompromiseDate                        Tag = 0x420020
	TagCompromiseOccurrenceDate              Tag = 0x420021
	TagContactInformation                    Tag = 0x420022
	TagCorrelationValue                      Tag = 0x4200d6
	TagCounterLength                         Tag = 0x4200d0
	TagCredential                            Tag = 0x420023
	TagCredentialType                        Tag = 0x420024
	TagCredentialValue                       Tag = 0x420025
	TagCriticalityIndicator                  Tag = 0x420026
	TagCryptographicAlgorithm                Tag = 0x420028
	TagCryptographicDomainParameters         Tag = 0x420029
	TagCryptographicLength                   Tag = 0x42002a
	TagCryptographicParameters               Tag = 0x42002b
	TagCryptographicUsageMask                Tag = 0x42002c
	TagCustomAttribute                       Tag = 0x42002d
	TagD                                     Tag = 0x42002e
	TagDRBGAlgorithm                         Tag = 0x4200db
	TagData                                  Tag = 0x4200c2
	TagDataLength                            Tag = 0x4200c4
	TagDeactivationDate                      Tag = 0x42002f
	TagDerivationData                        Tag = 0x420030
	TagDerivationMethod                      Tag = 0x420031
	TagDerivationParameters                  Tag = 0x420032
	TagDescription                           Tag = 0x4200fc
	TagDestroyAction                         Tag = 0x4200f3
	TagDestroyDate                           Tag = 0x420033
	TagDeviceIdentifier                      Tag = 0x4200a2
	TagDeviceSerialNumber                    Tag = 0x4200b0
	TagDigest                                Tag = 0x420034
	TagDigestValue                           Tag = 0x420035
	TagDigestedData                          Tag = 0x420107
	TagDigitalSignatureAlgorithm             Tag = 0x4200ae
	TagEncodingOption                        Tag = 0x4200a3
	TagEncryptionKeyInformation              Tag = 0x420036
	TagExtensionInformation                  Tag = 0x4200a4
	TagExtensionName                         Tag = 0x4200a5
	TagExtensionTag                          Tag = 0x4200a6
	TagExtensionType                         Tag = 0x4200a7
	TagExtractable                           Tag = 0x420122
	TagFIPS186Variation                      Tag = 0x4200dc
	TagFinalIndicator                        Tag = 0x4200d8
	TagFixedFieldLength                      Tag = 0x4200cf
	TagFresh                                 Tag = 0x4200a8
	TagG                                     Tag = 0x420037
	TagHashingAlgorithm                      Tag = 0x420038
	TagIVCounterNonce                        Tag = 0x42003d
	TagIVLength                              Tag = 0x4200cd
	TagInitIndicator                         Tag = 0x4200d7
	TagInitialCounterValue                   Tag = 0x4200d1
	TagInitialDate                           Tag = 0x420039
	TagInitializationVector                  Tag = 0x42003a
	TagInvocationFieldLength                 Tag = 0x4200d2
	TagIssuer                                Tag = 0x42003b
	TagIssuerAlternativeName                 Tag = 0x4200b1
	TagIssuerDistinguishedName               Tag = 0x4200b2
	TagIterationCount                        Tag = 0x42003c
	TagJ                                     Tag = 0x42003e
	TagKey                                   Tag = 0x42003f
	TagKeyBlock                              Tag = 0x420040
	TagKeyCompressionType                    Tag = 0x420041
	TagKeyFormatType                         Tag = 0x420042
	TagKeyMaterial                           Tag = 0x420043
	TagKeyPartIdentifier                     Tag = 0x420044
	TagKeyRoleType                           Tag = 0x420083
	TagKeyValue                              Tag = 0x420045
	TagKeyValueLocation                      Tag = 0x4200b8
	TagKeyValueLocationType                  Tag = 0x4200ba
	TagKeyValueLocationValue                 Tag = 0x4200b9
	TagKeyValuePresent                       Tag = 0x4200bb
	TagKeyWrapType                           Tag = 0x4200f8
	TagKeyWrappingData                       Tag = 0x420046
	TagKeyWrappingSpecification              Tag = 0x420047
	TagLastChangeDate                        Tag = 0x420048
	TagLeaseTime                             Tag = 0x420049
	TagLink                                  Tag = 0x42004a
	TagLinkType                              Tag = 0x42004b
	TagLinkedObjectIdentifier                Tag = 0x42004c
	TagLocatedItems                          Tag = 0x4200d5
	TagMACData                               Tag = 0x4200c6
	TagMACSignature                          Tag = 0x42004d
	TagMACSignatureKeyInformation            Tag = 0x42004e
	TagMachineIdentifier                     Tag = 0x4200a9
	TagMaskGenerator                         Tag = 0x420101
	TagMaskGeneratorHashingAlgorithm         Tag = 0x420102
	TagMaximumItems                          Tag = 0x42004f
	TagMaximumResponseSize                   Tag = 0x420050
	TagMediaIdentifier                       Tag = 0x4200aa
	TagMessageExtension                      Tag = 0x420051
	TagModulus                               Tag = 0x420052
	TagName                                  Tag = 0x420053
	TagNameType                              Tag = 0x420054
	TagNameValue                             Tag = 0x420055
	TagNetworkIdentifier                     Tag = 0x4200ab
	TagNeverExtractable                      Tag = 0x420123
	TagNonce                                 Tag = 0x4200c8
	TagNonceID                               Tag = 0x4200c9
	TagNonceValue                            Tag = 0x4200ca
	TagObjectGroup                           Tag = 0x420056
	TagObjectGroupMember                     Tag = 0x4200ac
	TagObjectType                            Tag = 0x420057
	TagOffset                                Tag = 0x420058
	TagOffsetItems                           Tag = 0x4200d4
	TagOpaqueDataType                        Tag = 0x420059
	TagOpaqueDataValue                       Tag = 0x42005a
	TagOpaqueObject                          Tag = 0x42005b
	TagOperation                             Tag = 0x42005c
	TagOperationPolicyName                   Tag = 0x42005d
	TagOriginalCreationDate                  Tag = 0x4200bc
	TagP                                     Tag = 0x42005e
	TagPGPKey                                Tag = 0x4200bd
	TagPGPKeyVersion                         Tag = 0x4200be
	TagPKCS_12FriendlyName                   Tag = 0x4200fb
	TagPSource                               Tag = 0x420103
	TagPaddingMethod                         Tag = 0x42005f
	TagPassword                              Tag = 0x4200a1
	TagPredictionResistance                  Tag = 0x4200dd
	TagPrimeExponentP                        Tag = 0x420060
	TagPrimeExponentQ                        Tag = 0x420061
	TagPrimeFieldSize                        Tag = 0x420062
	TagPrivateExponent                       Tag = 0x420063
	TagPrivateKey                            Tag = 0x420064
	TagPrivateKeyTemplateAttribute           Tag = 0x420065
	TagPrivateKeyUniqueIdentifier            Tag = 0x420066
	TagProcessStartDate                      Tag = 0x420067
	TagProfileInformation                    Tag = 0x4200eb
	TagProfileName                           Tag = 0x4200ec
	TagProtectStopDate                       Tag = 0x420068
	TagProtocolVersion                       Tag = 0x420069
	TagProtocolVersionMajor                  Tag = 0x42006a
	TagProtocolVersionMinor                  Tag = 0x42006b
	TagPublicExponent                        Tag = 0x42006c
	TagPublicKey                             Tag = 0x42006d
	TagPublicKeyTemplateAttribute            Tag = 0x42006e
	TagPublicKeyUniqueIdentifier             Tag = 0x42006f
	TagPutFunction                           Tag = 0x420070
	TagQ                                     Tag = 0x420071
	TagQString                               Tag = 0x420072
	TagQlength                               Tag = 0x420073
	TagQueryFunction                         Tag = 0x420074
	TagRNGAlgorithm                          Tag = 0x4200da
	TagRNGMode                               Tag = 0x4200f5
	TagRNGParameters                         Tag = 0x4200d9
	TagRandomIV                              Tag = 0x4200c5
	TagRandomNumberGenerator                 Tag = 0x4200de
	TagRecommendedCurve                      Tag = 0x420075
	TagReplaceExisting                       Tag = 0x420124
	TagReplacedUniqueIdentifier              Tag = 0x420076
	TagRequestHeader                         Tag = 0x420077
	TagRequestMessage                        Tag = 0x420078
	TagRequestPayload                        Tag = 0x420079
	TagResponseHeader                        Tag = 0x42007a
	TagResponseMessage                       Tag = 0x42007b
	TagResponsePayload                       Tag = 0x42007c
	TagResultMessage                         Tag = 0x42007d
	TagResultReason                          Tag = 0x42007e
	TagResultStatus                          Tag = 0x42007f
	TagRevocationMessage                     Tag = 0x420080
	TagRevocationReason                      Tag = 0x420081
	TagRevocationReasonCode                  Tag = 0x420082
	TagSalt                                  Tag = 0x420084
	TagSaltLength                            Tag = 0x420100
	TagSecretData                            Tag = 0x420085
	TagSecretDataType                        Tag = 0x420086
	TagSensitive                             Tag = 0x420120
	TagSerialNumber                          Tag = 0x420087
	TagServerCorrelationValue                Tag = 0x420106
	TagServerInformation                     Tag = 0x420088
	TagServerPort                            Tag = 0x4200ee
	TagServerURI                             Tag = 0x4200ed
	TagShreddingAlgorithm                    Tag = 0x4200f4
	TagSignatureData                         Tag = 0x4200c3
	TagSplitKey                              Tag = 0x420089
	TagSplitKeyMethod                        Tag = 0x42008a
	TagSplitKeyParts                         Tag = 0x42008b
	TagSplitKeyThreshold                     Tag = 0x42008c
	TagState                                 Tag = 0x42008d
	TagStorageStatusMask                     Tag = 0x42008e
	TagStreamingCapability                   Tag = 0x4200ef
	TagSubjectAlternativeName                Tag = 0x4200b3
	TagSubjectDistinguishedName              Tag = 0x4200b4
	TagSymmetricKey                          Tag = 0x42008f
	TagTagLength                             Tag = 0x4200ce
	TagTemplate                              Tag = 0x420090
	TagTemplateAttribute                     Tag = 0x420091
	TagTimeStamp                             Tag = 0x420092
	TagTrailerField                          Tag = 0x420104
	TagUniqueBatchItemID                     Tag = 0x420093
	TagUniqueIdentifier                      Tag = 0x420094
	TagUnwrapMode                            Tag = 0x4200f2
	TagUsageLimits                           Tag = 0x420095
	TagUsageLimitsCount                      Tag = 0x420096
	TagUsageLimitsTotal                      Tag = 0x420097
	TagUsageLimitsUnit                       Tag = 0x420098
	TagUsername                              Tag = 0x420099
	TagValidationAuthorityCountry            Tag = 0x4200e1
	TagValidationAuthorityType               Tag = 0x4200e0
	TagValidationAuthorityURI                Tag = 0x4200e2
	TagValidationCertificateIdentifier       Tag = 0x4200e7
	TagValidationCertificateURI              Tag = 0x4200e8
	TagValidationInformation                 Tag = 0x4200df
	TagValidationLevel                       Tag = 0x4200e6
	TagValidationProfile                     Tag = 0x4200ea
	TagValidationType                        Tag = 0x4200e5
	TagValidationVendorURI                   Tag = 0x4200e9
	TagValidationVersionMajor                Tag = 0x4200e3
	TagValidationVersionMinor                Tag = 0x4200e4
	TagValidityDate                          Tag = 0x42009a
	TagValidityIndicator                     Tag = 0x42009b
	TagVendorExtension                       Tag = 0x42009c
	TagVendorIdentification                  Tag = 0x42009d
	TagWrappingMethod                        Tag = 0x42009e
	TagX                                     Tag = 0x42009f
	TagX_509CertificateIdentifier            Tag = 0x4200b5
	TagX_509CertificateIssuer                Tag = 0x4200b6
	TagX_509CertificateSubject               Tag = 0x4200b7
	TagY                                     Tag = 0x4200a0
)

var _TagNameToValueMap = map[string]Tag{
	"ActivationDate":                        TagActivationDate,
	"AlternativeName":                       TagAlternativeName,
	"AlternativeNameType":                   TagAlternativeNameType,
	"AlternativeNameValue":                  TagAlternativeNameValue,
	"AlwaysSensitive":                       TagAlwaysSensitive,
	"ApplicationData":                       TagApplicationData,
	"ApplicationNamespace":                  TagApplicationNamespace,
	"ApplicationSpecificInformation":        TagApplicationSpecificInformation,
	"ArchiveDate":                           TagArchiveDate,
	"AsynchronousCapability":                TagAsynchronousCapability,
	"AsynchronousCorrelationValue":          TagAsynchronousCorrelationValue,
	"AsynchronousIndicator":                 TagAsynchronousIndicator,
	"AttestationAssertion":                  TagAttestationAssertion,
	"AttestationCapability":                 TagAttestationCapability,
	"AttestationCapableIndicator":           TagAttestationCapableIndicator,
	"AttestationMeasurement":                TagAttestationMeasurement,
	"AttestationType":                       TagAttestationType,
	"Attribute":                             TagAttribute,
	"AttributeIndex":                        TagAttributeIndex,
	"AttributeName":                         TagAttributeName,
	"AttributeValue":                        TagAttributeValue,
	"AuthenticatedEncryptionAdditionalData": TagAuthenticatedEncryptionAdditionalData,
	"AuthenticatedEncryptionTag":            TagAuthenticatedEncryptionTag,
	"Authentication":                        TagAuthentication,
	"BatchContinueCapability":               TagBatchContinueCapability,
	"BatchCount":                            TagBatchCount,
	"BatchErrorContinuationOption":          TagBatchErrorContinuationOption,
	"BatchItem":                             TagBatchItem,
	"BatchOrderOption":                      TagBatchOrderOption,
	"BatchUndoCapability":                   TagBatchUndoCapability,
	"BlockCipherMode":                       TagBlockCipherMode,
	"CRTCoefficient":                        TagCRTCoefficient,
	"CancellationResult":                    TagCancellationResult,
	"CapabilityInformation":                 TagCapabilityInformation,
	"Certificate":                           TagCertificate,
	"CertificateIdentifier":                 TagCertificateIdentifier,
	"CertificateIssuer":                     TagCertificateIssuer,
	"CertificateIssuerAlternativeName":      TagCertificateIssuerAlternativeName,
	"CertificateIssuerC":                    TagCertificateIssuerC,
	"CertificateIssuerCN":                   TagCertificateIssuerCN,
	"CertificateIssuerDC":                   TagCertificateIssuerDC,
	"CertificateIssuerDNQualifier":          TagCertificateIssuerDNQualifier,
	"CertificateIssuerDistinguishedName":    TagCertificateIssuerDistinguishedName,
	"CertificateIssuerEmail":                TagCertificateIssuerEmail,
	"CertificateIssuerL":                    TagCertificateIssuerL,
	"CertificateIssuerO":                    TagCertificateIssuerO,
	"CertificateIssuerOU":                   TagCertificateIssuerOU,
	"CertificateIssuerST":                   TagCertificateIssuerST,
	"CertificateIssuerSerialNumber":         TagCertificateIssuerSerialNumber,
	"CertificateIssuerTitle":                TagCertificateIssuerTitle,
	"CertificateIssuerUID":                  TagCertificateIssuerUID,
	"CertificateLength":                     TagCertificateLength,
	"CertificateRequest":                    TagCertificateRequest,
	"CertificateRequestType":                TagCertificateRequestType,
	"CertificateSerialNumber":               TagCertificateSerialNumber,
	"CertificateSubject":                    TagCertificateSubject,
	"CertificateSubjectAlternativeName":     TagCertificateSubjectAlternativeName,
	"CertificateSubjectC":                   TagCertificateSubjectC,
	"CertificateSubjectCN":                  TagCertificateSubjectCN,
	"CertificateSubjectDC":                  TagCertificateSubjectDC,
	"CertificateSubjectDNQualifier":         TagCertificateSubjectDNQualifier,
	"CertificateSubjectDistinguishedName":   TagCertificateSubjectDistinguishedName,
	"CertificateSubjectEmail":               TagCertificateSubjectEmail,
	"CertificateSubjectL":                   TagCertificateSubjectL,
	"CertificateSubjectO":                   TagCertificateSubjectO,
	"CertificateSubjectOU":                  TagCertificateSubjectOU,
	"CertificateSubjectST":                  TagCertificateSubjectST,
	"CertificateSubjectSerialNumber":        TagCertificateSubjectSerialNumber,
	"CertificateSubjectTitle":               TagCertificateSubjectTitle,
	"CertificateSubjectUID":                 TagCertificateSubjectUID,
	"CertificateType":                       TagCertificateType,
	"CertificateValue":                      TagCertificateValue,
	"ClientCorrelationValue":                TagClientCorrelationValue,
	"ClientRegistrationMethod":              TagClientRegistrationMethod,
	"Comment":                               TagComment,
	"CommonTemplateAttribute":               TagCommonTemplateAttribute,
	"CompromiseDate":                        TagCompromiseDate,
	"CompromiseOccurrenceDate":              TagCompromiseOccurrenceDate,
	"ContactInformation":                    TagContactInformation,
	"CorrelationValue":                      TagCorrelationValue,
	"CounterLength":                         TagCounterLength,
	"Credential":                            TagCredential,
	"CredentialType":                        TagCredentialType,
	"CredentialValue":                       TagCredentialValue,
	"CriticalityIndicator":                  TagCriticalityIndicator,
	"CryptographicAlgorithm":                TagCryptographicAlgorithm,
	"CryptographicDomainParameters":         TagCryptographicDomainParameters,
	"CryptographicLength":                   TagCryptographicLength,
	"CryptographicParameters":               TagCryptographicParameters,
	"CryptographicUsageMask":                TagCryptographicUsageMask,
	"CustomAttribute":                       TagCustomAttribute,
	"D":                                     TagD,
	"DRBGAlgorithm":                         TagDRBGAlgorithm,
	"Data":                                  TagData,
	"DataLength":                            TagDataLength,
	"DeactivationDate":                      TagDeactivationDate,
	"DerivationData":                        TagDerivationData,
	"DerivationMethod":                      TagDerivationMethod,
	"DerivationParameters":                  TagDerivationParameters,
	"Description":                           TagDescription,
	"DestroyAction":                         TagDestroyAction,
	"DestroyDate":                           TagDestroyDate,
	"DeviceIdentifier":                      TagDeviceIdentifier,
	"DeviceSerialNumber":                    TagDeviceSerialNumber,
	"Digest":                                TagDigest,
	"DigestValue":                           TagDigestValue,
	"DigestedData":                          TagDigestedData,
	"DigitalSignatureAlgorithm":             TagDigitalSignatureAlgorithm,
	"EncodingOption":                        TagEncodingOption,
	"EncryptionKeyInformation":              TagEncryptionKeyInformation,
	"ExtensionInformation":                  TagExtensionInformation,
	"ExtensionName":                         TagExtensionName,
	"ExtensionTag":                          TagExtensionTag,
	"ExtensionType":                         TagExtensionType,
	"Extractable":                           TagExtractable,
	"FIPS186Variation":                      TagFIPS186Variation,
	"FinalIndicator":                        TagFinalIndicator,
	"FixedFieldLength":                      TagFixedFieldLength,
	"Fresh":                                 TagFresh,
	"G":                                     TagG,
	"HashingAlgorithm":                      TagHashingAlgorithm,
	"IVCounterNonce":                        TagIVCounterNonce,
	"IVLength":                              TagIVLength,
	"InitIndicator":                         TagInitIndicator,
	"InitialCounterValue":                   TagInitialCounterValue,
	"InitialDate":                           TagInitialDate,
	"InitializationVector":                  TagInitializationVector,
	"InvocationFieldLength":                 TagInvocationFieldLength,
	"Issuer":                                TagIssuer,
	"IssuerAlternativeName":                 TagIssuerAlternativeName,
	"IssuerDistinguishedName":               TagIssuerDistinguishedName,
	"IterationCount":                        TagIterationCount,
	"J":                                     TagJ,
	"Key":                                   TagKey,
	"KeyBlock":                              TagKeyBlock,
	"KeyCompressionType":                    TagKeyCompressionType,
	"KeyFormatType":                         TagKeyFormatType,
	"KeyMaterial":                           TagKeyMaterial,
	"KeyPartIdentifier":                     TagKeyPartIdentifier,
	"KeyRoleType":                           TagKeyRoleType,
	"KeyValue":                              TagKeyValue,
	"KeyValueLocation":                      TagKeyValueLocation,
	"KeyValueLocationType":                  TagKeyValueLocationType,
	"KeyValueLocationValue":                 TagKeyValueLocationValue,
	"KeyValuePresent":                       TagKeyValuePresent,
	"KeyWrapType":                           TagKeyWrapType,
	"KeyWrappingData":                       TagKeyWrappingData,
	"KeyWrappingSpecification":              TagKeyWrappingSpecification,
	"LastChangeDate":                        TagLastChangeDate,
	"LeaseTime":                             TagLeaseTime,
	"Link":                                  TagLink,
	"LinkType":                              TagLinkType,
	"LinkedObjectIdentifier":                TagLinkedObjectIdentifier,
	"LocatedItems":                          TagLocatedItems,
	"MACData":                               TagMACData,
	"MACSignature":                          TagMACSignature,
	"MACSignatureKeyInformation":            TagMACSignatureKeyInformation,
	"MachineIdentifier":                     TagMachineIdentifier,
	"MaskGenerator":                         TagMaskGenerator,
	"MaskGeneratorHashingAlgorithm":         TagMaskGeneratorHashingAlgorithm,
	"MaximumItems":                          TagMaximumItems,
	"MaximumResponseSize":                   TagMaximumResponseSize,
	"MediaIdentifier":                       TagMediaIdentifier,
	"MessageExtension":                      TagMessageExtension,
	"Modulus":                               TagModulus,
	"Name":                                  TagName,
	"NameType":                              TagNameType,
	"NameValue":                             TagNameValue,
	"NetworkIdentifier":                     TagNetworkIdentifier,
	"NeverExtractable":                      TagNeverExtractable,
	"Nonce":                                 TagNonce,
	"NonceID":                               TagNonceID,
	"NonceValue":                            TagNonceValue,
	"ObjectGroup":                           TagObjectGroup,
	"ObjectGroupMember":                     TagObjectGroupMember,
	"ObjectType":                            TagObjectType,
	"Offset":                                TagOffset,
	"OffsetItems":                           TagOffsetItems,
	"OpaqueDataType":                        TagOpaqueDataType,
	"OpaqueDataValue":                       TagOpaqueDataValue,
	"OpaqueObject":                          TagOpaqueObject,
	"Operation":                             TagOperation,
	"OperationPolicyName":                   TagOperationPolicyName,
	"OriginalCreationDate":                  TagOriginalCreationDate,
	"P":                               TagP,
	"PGPKey":                          TagPGPKey,
	"PGPKeyVersion":                   TagPGPKeyVersion,
	"PKCS_12FriendlyName":             TagPKCS_12FriendlyName,
	"PSource":                         TagPSource,
	"PaddingMethod":                   TagPaddingMethod,
	"Password":                        TagPassword,
	"PredictionResistance":            TagPredictionResistance,
	"PrimeExponentP":                  TagPrimeExponentP,
	"PrimeExponentQ":                  TagPrimeExponentQ,
	"PrimeFieldSize":                  TagPrimeFieldSize,
	"PrivateExponent":                 TagPrivateExponent,
	"PrivateKey":                      TagPrivateKey,
	"PrivateKeyTemplateAttribute":     TagPrivateKeyTemplateAttribute,
	"PrivateKeyUniqueIdentifier":      TagPrivateKeyUniqueIdentifier,
	"ProcessStartDate":                TagProcessStartDate,
	"ProfileInformation":              TagProfileInformation,
	"ProfileName":                     TagProfileName,
	"ProtectStopDate":                 TagProtectStopDate,
	"ProtocolVersion":                 TagProtocolVersion,
	"ProtocolVersionMajor":            TagProtocolVersionMajor,
	"ProtocolVersionMinor":            TagProtocolVersionMinor,
	"PublicExponent":                  TagPublicExponent,
	"PublicKey":                       TagPublicKey,
	"PublicKeyTemplateAttribute":      TagPublicKeyTemplateAttribute,
	"PublicKeyUniqueIdentifier":       TagPublicKeyUniqueIdentifier,
	"PutFunction":                     TagPutFunction,
	"Q":                               TagQ,
	"QString":                         TagQString,
	"Qlength":                         TagQlength,
	"QueryFunction":                   TagQueryFunction,
	"RNGAlgorithm":                    TagRNGAlgorithm,
	"RNGMode":                         TagRNGMode,
	"RNGParameters":                   TagRNGParameters,
	"RandomIV":                        TagRandomIV,
	"RandomNumberGenerator":           TagRandomNumberGenerator,
	"RecommendedCurve":                TagRecommendedCurve,
	"ReplaceExisting":                 TagReplaceExisting,
	"ReplacedUniqueIdentifier":        TagReplacedUniqueIdentifier,
	"RequestHeader":                   TagRequestHeader,
	"RequestMessage":                  TagRequestMessage,
	"RequestPayload":                  TagRequestPayload,
	"ResponseHeader":                  TagResponseHeader,
	"ResponseMessage":                 TagResponseMessage,
	"ResponsePayload":                 TagResponsePayload,
	"ResultMessage":                   TagResultMessage,
	"ResultReason":                    TagResultReason,
	"ResultStatus":                    TagResultStatus,
	"RevocationMessage":               TagRevocationMessage,
	"RevocationReason":                TagRevocationReason,
	"RevocationReasonCode":            TagRevocationReasonCode,
	"Salt":                            TagSalt,
	"SaltLength":                      TagSaltLength,
	"SecretData":                      TagSecretData,
	"SecretDataType":                  TagSecretDataType,
	"Sensitive":                       TagSensitive,
	"SerialNumber":                    TagSerialNumber,
	"ServerCorrelationValue":          TagServerCorrelationValue,
	"ServerInformation":               TagServerInformation,
	"ServerPort":                      TagServerPort,
	"ServerURI":                       TagServerURI,
	"ShreddingAlgorithm":              TagShreddingAlgorithm,
	"SignatureData":                   TagSignatureData,
	"SplitKey":                        TagSplitKey,
	"SplitKeyMethod":                  TagSplitKeyMethod,
	"SplitKeyParts":                   TagSplitKeyParts,
	"SplitKeyThreshold":               TagSplitKeyThreshold,
	"State":                           TagState,
	"StorageStatusMask":               TagStorageStatusMask,
	"StreamingCapability":             TagStreamingCapability,
	"SubjectAlternativeName":          TagSubjectAlternativeName,
	"SubjectDistinguishedName":        TagSubjectDistinguishedName,
	"SymmetricKey":                    TagSymmetricKey,
	"TagLength":                       TagTagLength,
	"Template":                        TagTemplate,
	"TemplateAttribute":               TagTemplateAttribute,
	"TimeStamp":                       TagTimeStamp,
	"TrailerField":                    TagTrailerField,
	"UniqueBatchItemID":               TagUniqueBatchItemID,
	"UniqueIdentifier":                TagUniqueIdentifier,
	"UnwrapMode":                      TagUnwrapMode,
	"UsageLimits":                     TagUsageLimits,
	"UsageLimitsCount":                TagUsageLimitsCount,
	"UsageLimitsTotal":                TagUsageLimitsTotal,
	"UsageLimitsUnit":                 TagUsageLimitsUnit,
	"Username":                        TagUsername,
	"ValidationAuthorityCountry":      TagValidationAuthorityCountry,
	"ValidationAuthorityType":         TagValidationAuthorityType,
	"ValidationAuthorityURI":          TagValidationAuthorityURI,
	"ValidationCertificateIdentifier": TagValidationCertificateIdentifier,
	"ValidationCertificateURI":        TagValidationCertificateURI,
	"ValidationInformation":           TagValidationInformation,
	"ValidationLevel":                 TagValidationLevel,
	"ValidationProfile":               TagValidationProfile,
	"ValidationType":                  TagValidationType,
	"ValidationVendorURI":             TagValidationVendorURI,
	"ValidationVersionMajor":          TagValidationVersionMajor,
	"ValidationVersionMinor":          TagValidationVersionMinor,
	"ValidityDate":                    TagValidityDate,
	"ValidityIndicator":               TagValidityIndicator,
	"VendorExtension":                 TagVendorExtension,
	"VendorIdentification":            TagVendorIdentification,
	"WrappingMethod":                  TagWrappingMethod,
	"X":                               TagX,
	"X_509CertificateIdentifier": TagX_509CertificateIdentifier,
	"X_509CertificateIssuer":     TagX_509CertificateIssuer,
	"X_509CertificateSubject":    TagX_509CertificateSubject,
	"Y": TagY,
}

var _TagValueToNameMap = map[Tag]string{
	TagActivationDate:                        "ActivationDate",
	TagAlternativeName:                       "AlternativeName",
	TagAlternativeNameType:                   "AlternativeNameType",
	TagAlternativeNameValue:                  "AlternativeNameValue",
	TagAlwaysSensitive:                       "AlwaysSensitive",
	TagApplicationData:                       "ApplicationData",
	TagApplicationNamespace:                  "ApplicationNamespace",
	TagApplicationSpecificInformation:        "ApplicationSpecificInformation",
	TagArchiveDate:                           "ArchiveDate",
	TagAsynchronousCapability:                "AsynchronousCapability",
	TagAsynchronousCorrelationValue:          "AsynchronousCorrelationValue",
	TagAsynchronousIndicator:                 "AsynchronousIndicator",
	TagAttestationAssertion:                  "AttestationAssertion",
	TagAttestationCapability:                 "AttestationCapability",
	TagAttestationCapableIndicator:           "AttestationCapableIndicator",
	TagAttestationMeasurement:                "AttestationMeasurement",
	TagAttestationType:                       "AttestationType",
	TagAttribute:                             "Attribute",
	TagAttributeIndex:                        "AttributeIndex",
	TagAttributeName:                         "AttributeName",
	TagAttributeValue:                        "AttributeValue",
	TagAuthenticatedEncryptionAdditionalData: "AuthenticatedEncryptionAdditionalData",
	TagAuthenticatedEncryptionTag:            "AuthenticatedEncryptionTag",
	TagAuthentication:                        "Authentication",
	TagBatchContinueCapability:               "BatchContinueCapability",
	TagBatchCount:                            "BatchCount",
	TagBatchErrorContinuationOption:          "BatchErrorContinuationOption",
	TagBatchItem:                             "BatchItem",
	TagBatchOrderOption:                      "BatchOrderOption",
	TagBatchUndoCapability:                   "BatchUndoCapability",
	TagBlockCipherMode:                       "BlockCipherMode",
	TagCRTCoefficient:                        "CRTCoefficient",
	TagCancellationResult:                    "CancellationResult",
	TagCapabilityInformation:                 "CapabilityInformation",
	TagCertificate:                           "Certificate",
	TagCertificateIdentifier:                 "CertificateIdentifier",
	TagCertificateIssuer:                     "CertificateIssuer",
	TagCertificateIssuerAlternativeName:      "CertificateIssuerAlternativeName",
	TagCertificateIssuerC:                    "CertificateIssuerC",
	TagCertificateIssuerCN:                   "CertificateIssuerCN",
	TagCertificateIssuerDC:                   "CertificateIssuerDC",
	TagCertificateIssuerDNQualifier:          "CertificateIssuerDNQualifier",
	TagCertificateIssuerDistinguishedName:    "CertificateIssuerDistinguishedName",
	TagCertificateIssuerEmail:                "CertificateIssuerEmail",
	TagCertificateIssuerL:                    "CertificateIssuerL",
	TagCertificateIssuerO:                    "CertificateIssuerO",
	TagCertificateIssuerOU:                   "CertificateIssuerOU",
	TagCertificateIssuerST:                   "CertificateIssuerST",
	TagCertificateIssuerSerialNumber:         "CertificateIssuerSerialNumber",
	TagCertificateIssuerTitle:                "CertificateIssuerTitle",
	TagCertificateIssuerUID:                  "CertificateIssuerUID",
	TagCertificateLength:                     "CertificateLength",
	TagCertificateRequest:                    "CertificateRequest",
	TagCertificateRequestType:                "CertificateRequestType",
	TagCertificateSerialNumber:               "CertificateSerialNumber",
	TagCertificateSubject:                    "CertificateSubject",
	TagCertificateSubjectAlternativeName:     "CertificateSubjectAlternativeName",
	TagCertificateSubjectC:                   "CertificateSubjectC",
	TagCertificateSubjectCN:                  "CertificateSubjectCN",
	TagCertificateSubjectDC:                  "CertificateSubjectDC",
	TagCertificateSubjectDNQualifier:         "CertificateSubjectDNQualifier",
	TagCertificateSubjectDistinguishedName:   "CertificateSubjectDistinguishedName",
	TagCertificateSubjectEmail:               "CertificateSubjectEmail",
	TagCertificateSubjectL:                   "CertificateSubjectL",
	TagCertificateSubjectO:                   "CertificateSubjectO",
	TagCertificateSubjectOU:                  "CertificateSubjectOU",
	TagCertificateSubjectST:                  "CertificateSubjectST",
	TagCertificateSubjectSerialNumber:        "CertificateSubjectSerialNumber",
	TagCertificateSubjectTitle:               "CertificateSubjectTitle",
	TagCertificateSubjectUID:                 "CertificateSubjectUID",
	TagCertificateType:                       "CertificateType",
	TagCertificateValue:                      "CertificateValue",
	TagClientCorrelationValue:                "ClientCorrelationValue",
	TagClientRegistrationMethod:              "ClientRegistrationMethod",
	TagComment:                               "Comment",
	TagCommonTemplateAttribute:               "CommonTemplateAttribute",
	TagCompromiseDate:                        "CompromiseDate",
	TagCompromiseOccurrenceDate:              "CompromiseOccurrenceDate",
	TagContactInformation:                    "ContactInformation",
	TagCorrelationValue:                      "CorrelationValue",
	TagCounterLength:                         "CounterLength",
	TagCredential:                            "Credential",
	TagCredentialType:                        "CredentialType",
	TagCredentialValue:                       "CredentialValue",
	TagCriticalityIndicator:                  "CriticalityIndicator",
	TagCryptographicAlgorithm:                "CryptographicAlgorithm",
	TagCryptographicDomainParameters:         "CryptographicDomainParameters",
	TagCryptographicLength:                   "CryptographicLength",
	TagCryptographicParameters:               "CryptographicParameters",
	TagCryptographicUsageMask:                "CryptographicUsageMask",
	TagCustomAttribute:                       "CustomAttribute",
	TagD:                                     "D",
	TagDRBGAlgorithm:                         "DRBGAlgorithm",
	TagData:                                  "Data",
	TagDataLength:                            "DataLength",
	TagDeactivationDate:                      "DeactivationDate",
	TagDerivationData:                        "DerivationData",
	TagDerivationMethod:                      "DerivationMethod",
	TagDerivationParameters:                  "DerivationParameters",
	TagDescription:                           "Description",
	TagDestroyAction:                         "DestroyAction",
	TagDestroyDate:                           "DestroyDate",
	TagDeviceIdentifier:                      "DeviceIdentifier",
	TagDeviceSerialNumber:                    "DeviceSerialNumber",
	TagDigest:                                "Digest",
	TagDigestValue:                           "DigestValue",
	TagDigestedData:                          "DigestedData",
	TagDigitalSignatureAlgorithm:             "DigitalSignatureAlgorithm",
	TagEncodingOption:                        "EncodingOption",
	TagEncryptionKeyInformation:              "EncryptionKeyInformation",
	TagExtensionInformation:                  "ExtensionInformation",
	TagExtensionName:                         "ExtensionName",
	TagExtensionTag:                          "ExtensionTag",
	TagExtensionType:                         "ExtensionType",
	TagExtractable:                           "Extractable",
	TagFIPS186Variation:                      "FIPS186Variation",
	TagFinalIndicator:                        "FinalIndicator",
	TagFixedFieldLength:                      "FixedFieldLength",
	TagFresh:                                 "Fresh",
	TagG:                                     "G",
	TagHashingAlgorithm:                      "HashingAlgorithm",
	TagIVCounterNonce:                        "IVCounterNonce",
	TagIVLength:                              "IVLength",
	TagInitIndicator:                         "InitIndicator",
	TagInitialCounterValue:                   "InitialCounterValue",
	TagInitialDate:                           "InitialDate",
	TagInitializationVector:                  "InitializationVector",
	TagInvocationFieldLength:                 "InvocationFieldLength",
	TagIssuer:                                "Issuer",
	TagIssuerAlternativeName:                 "IssuerAlternativeName",
	TagIssuerDistinguishedName:               "IssuerDistinguishedName",
	TagIterationCount:                        "IterationCount",
	TagJ:                                     "J",
	TagKey:                                   "Key",
	TagKeyBlock:                              "KeyBlock",
	TagKeyCompressionType:                    "KeyCompressionType",
	TagKeyFormatType:                         "KeyFormatType",
	TagKeyMaterial:                           "KeyMaterial",
	TagKeyPartIdentifier:                     "KeyPartIdentifier",
	TagKeyRoleType:                           "KeyRoleType",
	TagKeyValue:                              "KeyValue",
	TagKeyValueLocation:                      "KeyValueLocation",
	TagKeyValueLocationType:                  "KeyValueLocationType",
	TagKeyValueLocationValue:                 "KeyValueLocationValue",
	TagKeyValuePresent:                       "KeyValuePresent",
	TagKeyWrapType:                           "KeyWrapType",
	TagKeyWrappingData:                       "KeyWrappingData",
	TagKeyWrappingSpecification:              "KeyWrappingSpecification",
	TagLastChangeDate:                        "LastChangeDate",
	TagLeaseTime:                             "LeaseTime",
	TagLink:                                  "Link",
	TagLinkType:                              "LinkType",
	TagLinkedObjectIdentifier:                "LinkedObjectIdentifier",
	TagLocatedItems:                          "LocatedItems",
	TagMACData:                               "MACData",
	TagMACSignature:                          "MACSignature",
	TagMACSignatureKeyInformation:            "MACSignatureKeyInformation",
	TagMachineIdentifier:                     "MachineIdentifier",
	TagMaskGenerator:                         "MaskGenerator",
	TagMaskGeneratorHashingAlgorithm:         "MaskGeneratorHashingAlgorithm",
	TagMaximumItems:                          "MaximumItems",
	TagMaximumResponseSize:                   "MaximumResponseSize",
	TagMediaIdentifier:                       "MediaIdentifier",
	TagMessageExtension:                      "MessageExtension",
	TagModulus:                               "Modulus",
	TagName:                                  "Name",
	TagNameType:                              "NameType",
	TagNameValue:                             "NameValue",
	TagNetworkIdentifier:                     "NetworkIdentifier",
	TagNeverExtractable:                      "NeverExtractable",
	TagNonce:                                 "Nonce",
	TagNonceID:                               "NonceID",
	TagNonceValue:                            "NonceValue",
	TagObjectGroup:                           "ObjectGroup",
	TagObjectGroupMember:                     "ObjectGroupMember",
	TagObjectType:                            "ObjectType",
	TagOffset:                                "Offset",
	TagOffsetItems:                           "OffsetItems",
	TagOpaqueDataType:                        "OpaqueDataType",
	TagOpaqueDataValue:                       "OpaqueDataValue",
	TagOpaqueObject:                          "OpaqueObject",
	TagOperation:                             "Operation",
	TagOperationPolicyName:                   "OperationPolicyName",
	TagOriginalCreationDate:                  "OriginalCreationDate",
	TagP:                               "P",
	TagPGPKey:                          "PGPKey",
	TagPGPKeyVersion:                   "PGPKeyVersion",
	TagPKCS_12FriendlyName:             "PKCS_12FriendlyName",
	TagPSource:                         "PSource",
	TagPaddingMethod:                   "PaddingMethod",
	TagPassword:                        "Password",
	TagPredictionResistance:            "PredictionResistance",
	TagPrimeExponentP:                  "PrimeExponentP",
	TagPrimeExponentQ:                  "PrimeExponentQ",
	TagPrimeFieldSize:                  "PrimeFieldSize",
	TagPrivateExponent:                 "PrivateExponent",
	TagPrivateKey:                      "PrivateKey",
	TagPrivateKeyTemplateAttribute:     "PrivateKeyTemplateAttribute",
	TagPrivateKeyUniqueIdentifier:      "PrivateKeyUniqueIdentifier",
	TagProcessStartDate:                "ProcessStartDate",
	TagProfileInformation:              "ProfileInformation",
	TagProfileName:                     "ProfileName",
	TagProtectStopDate:                 "ProtectStopDate",
	TagProtocolVersion:                 "ProtocolVersion",
	TagProtocolVersionMajor:            "ProtocolVersionMajor",
	TagProtocolVersionMinor:            "ProtocolVersionMinor",
	TagPublicExponent:                  "PublicExponent",
	TagPublicKey:                       "PublicKey",
	TagPublicKeyTemplateAttribute:      "PublicKeyTemplateAttribute",
	TagPublicKeyUniqueIdentifier:       "PublicKeyUniqueIdentifier",
	TagPutFunction:                     "PutFunction",
	TagQ:                               "Q",
	TagQString:                         "QString",
	TagQlength:                         "Qlength",
	TagQueryFunction:                   "QueryFunction",
	TagRNGAlgorithm:                    "RNGAlgorithm",
	TagRNGMode:                         "RNGMode",
	TagRNGParameters:                   "RNGParameters",
	TagRandomIV:                        "RandomIV",
	TagRandomNumberGenerator:           "RandomNumberGenerator",
	TagRecommendedCurve:                "RecommendedCurve",
	TagReplaceExisting:                 "ReplaceExisting",
	TagReplacedUniqueIdentifier:        "ReplacedUniqueIdentifier",
	TagRequestHeader:                   "RequestHeader",
	TagRequestMessage:                  "RequestMessage",
	TagRequestPayload:                  "RequestPayload",
	TagResponseHeader:                  "ResponseHeader",
	TagResponseMessage:                 "ResponseMessage",
	TagResponsePayload:                 "ResponsePayload",
	TagResultMessage:                   "ResultMessage",
	TagResultReason:                    "ResultReason",
	TagResultStatus:                    "ResultStatus",
	TagRevocationMessage:               "RevocationMessage",
	TagRevocationReason:                "RevocationReason",
	TagRevocationReasonCode:            "RevocationReasonCode",
	TagSalt:                            "Salt",
	TagSaltLength:                      "SaltLength",
	TagSecretData:                      "SecretData",
	TagSecretDataType:                  "SecretDataType",
	TagSensitive:                       "Sensitive",
	TagSerialNumber:                    "SerialNumber",
	TagServerCorrelationValue:          "ServerCorrelationValue",
	TagServerInformation:               "ServerInformation",
	TagServerPort:                      "ServerPort",
	TagServerURI:                       "ServerURI",
	TagShreddingAlgorithm:              "ShreddingAlgorithm",
	TagSignatureData:                   "SignatureData",
	TagSplitKey:                        "SplitKey",
	TagSplitKeyMethod:                  "SplitKeyMethod",
	TagSplitKeyParts:                   "SplitKeyParts",
	TagSplitKeyThreshold:               "SplitKeyThreshold",
	TagState:                           "State",
	TagStorageStatusMask:               "StorageStatusMask",
	TagStreamingCapability:             "StreamingCapability",
	TagSubjectAlternativeName:          "SubjectAlternativeName",
	TagSubjectDistinguishedName:        "SubjectDistinguishedName",
	TagSymmetricKey:                    "SymmetricKey",
	TagTagLength:                       "TagLength",
	TagTemplate:                        "Template",
	TagTemplateAttribute:               "TemplateAttribute",
	TagTimeStamp:                       "TimeStamp",
	TagTrailerField:                    "TrailerField",
	TagUniqueBatchItemID:               "UniqueBatchItemID",
	TagUniqueIdentifier:                "UniqueIdentifier",
	TagUnwrapMode:                      "UnwrapMode",
	TagUsageLimits:                     "UsageLimits",
	TagUsageLimitsCount:                "UsageLimitsCount",
	TagUsageLimitsTotal:                "UsageLimitsTotal",
	TagUsageLimitsUnit:                 "UsageLimitsUnit",
	TagUsername:                        "Username",
	TagValidationAuthorityCountry:      "ValidationAuthorityCountry",
	TagValidationAuthorityType:         "ValidationAuthorityType",
	TagValidationAuthorityURI:          "ValidationAuthorityURI",
	TagValidationCertificateIdentifier: "ValidationCertificateIdentifier",
	TagValidationCertificateURI:        "ValidationCertificateURI",
	TagValidationInformation:           "ValidationInformation",
	TagValidationLevel:                 "ValidationLevel",
	TagValidationProfile:               "ValidationProfile",
	TagValidationType:                  "ValidationType",
	TagValidationVendorURI:             "ValidationVendorURI",
	TagValidationVersionMajor:          "ValidationVersionMajor",
	TagValidationVersionMinor:          "ValidationVersionMinor",
	TagValidityDate:                    "ValidityDate",
	TagValidityIndicator:               "ValidityIndicator",
	TagVendorExtension:                 "VendorExtension",
	TagVendorIdentification:            "VendorIdentification",
	TagWrappingMethod:                  "WrappingMethod",
	TagX:                               "X",
	TagX_509CertificateIdentifier: "X_509CertificateIdentifier",
	TagX_509CertificateIssuer:     "X_509CertificateIssuer",
	TagX_509CertificateSubject:    "X_509CertificateSubject",
	TagY: "Y",
}

func (t Tag) String() string {
	if s, ok := _TagValueToNameMap[t]; ok {
		return s
	}
	return fmt.Sprintf("%#06x", uint32(t))
}

func ParseTag(s string) (Tag, error) {
	if strings.HasPrefix(s, "0x") {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		switch len(b) {
		case 6:
			b = append([]byte{0}, b...)
		case 8:
		default:
			return Tag(0), fmt.Errorf("invalid byte length for tag, should be 3 bytes: %s", s)
		}

		return Tag(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _TagNameToValueMap[s]; ok {
		return v, nil
	} else {
		return Tag(0), fmt.Errorf("%s is not a valid Tag", s)
	}
}

func (t Tag) MarshalText() (text []byte, err error) {
	return []byte(t.String()), nil
}

func (t *Tag) UnmarshalText(text []byte) (err error) {
	*t, err = ParseTag(string(text))
	return
}
