// Code generated by "kmipenums "; DO NOT EDIT.

package kmip

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strings"
)

// Tag
// 9.1.3.1
type Tag uint32

const (
	TagActivationDate                        Tag = 0x420001
	TagAlternativeName                       Tag = 0x4200bf
	TagAlternativeNameType                   Tag = 0x4200c1
	TagAlternativeNameValue                  Tag = 0x4200c0
	TagAlwaysSensitive                       Tag = 0x420121
	TagApplicationData                       Tag = 0x420002
	TagApplicationNamespace                  Tag = 0x420003
	TagApplicationSpecificInformation        Tag = 0x420004
	TagArchiveDate                           Tag = 0x420005
	TagAsynchronousCapability                Tag = 0x4200f0
	TagAsynchronousCorrelationValue          Tag = 0x420006
	TagAsynchronousIndicator                 Tag = 0x420007
	TagAttestationAssertion                  Tag = 0x4200cc
	TagAttestationCapability                 Tag = 0x4200f1
	TagAttestationCapableIndicator           Tag = 0x4200d3
	TagAttestationMeasurement                Tag = 0x4200cb
	TagAttestationType                       Tag = 0x4200c7
	TagAttribute                             Tag = 0x420008
	TagAttributeIndex                        Tag = 0x420009
	TagAttributeName                         Tag = 0x42000a
	TagAttributeValue                        Tag = 0x42000b
	TagAuthenticatedEncryptionAdditionalData Tag = 0x4200fe
	TagAuthenticatedEncryptionTag            Tag = 0x4200ff
	TagAuthentication                        Tag = 0x42000c
	TagBatchContinueCapability               Tag = 0x4200fa
	TagBatchCount                            Tag = 0x42000d
	TagBatchErrorContinuationOption          Tag = 0x42000e
	TagBatchItem                             Tag = 0x42000f
	TagBatchOrderOption                      Tag = 0x420010
	TagBatchUndoCapability                   Tag = 0x4200f9
	TagBlockCipherMode                       Tag = 0x420011
	TagCRTCoefficient                        Tag = 0x420027
	TagCancellationResult                    Tag = 0x420012
	TagCapabilityInformation                 Tag = 0x4200f7
	TagCertificate                           Tag = 0x420013
	TagCertificateIdentifier                 Tag = 0x420014
	TagCertificateIssuer                     Tag = 0x420015
	TagCertificateIssuerAlternativeName      Tag = 0x420016
	TagCertificateIssuerC                    Tag = 0x420118
	TagCertificateIssuerCN                   Tag = 0x420114
	TagCertificateIssuerDC                   Tag = 0x42011e
	TagCertificateIssuerDNQualifier          Tag = 0x42011f
	TagCertificateIssuerDistinguishedName    Tag = 0x420017
	TagCertificateIssuerEmail                Tag = 0x420117
	TagCertificateIssuerL                    Tag = 0x42011a
	TagCertificateIssuerO                    Tag = 0x420115
	TagCertificateIssuerOU                   Tag = 0x420116
	TagCertificateIssuerST                   Tag = 0x420119
	TagCertificateIssuerSerialNumber         Tag = 0x42011c
	TagCertificateIssuerTitle                Tag = 0x42011d
	TagCertificateIssuerUID                  Tag = 0x42011b
	TagCertificateLength                     Tag = 0x4200ad
	TagCertificateRequest                    Tag = 0x420018
	TagCertificateRequestType                Tag = 0x420019
	TagCertificateSerialNumber               Tag = 0x4200af
	TagCertificateSubject                    Tag = 0x42001a
	TagCertificateSubjectAlternativeName     Tag = 0x42001b
	TagCertificateSubjectC                   Tag = 0x42010c
	TagCertificateSubjectCN                  Tag = 0x420108
	TagCertificateSubjectDC                  Tag = 0x420112
	TagCertificateSubjectDNQualifier         Tag = 0x420113
	TagCertificateSubjectDistinguishedName   Tag = 0x42001c
	TagCertificateSubjectEmail               Tag = 0x42010b
	TagCertificateSubjectL                   Tag = 0x42010e
	TagCertificateSubjectO                   Tag = 0x420109
	TagCertificateSubjectOU                  Tag = 0x42010a
	TagCertificateSubjectST                  Tag = 0x42010d
	TagCertificateSubjectSerialNumber        Tag = 0x420110
	TagCertificateSubjectTitle               Tag = 0x420111
	TagCertificateSubjectUID                 Tag = 0x42010f
	TagCertificateType                       Tag = 0x42001d
	TagCertificateValue                      Tag = 0x42001e
	TagClientCorrelationValue                Tag = 0x420105
	TagClientRegistrationMethod              Tag = 0x4200f6
	TagComment                               Tag = 0x4200fd
	TagCommonTemplateAttribute               Tag = 0x42001f
	TagCompromiseDate                        Tag = 0x420020
	TagCompromiseOccurrenceDate              Tag = 0x420021
	TagContactInformation                    Tag = 0x420022
	TagCorrelationValue                      Tag = 0x4200d6
	TagCounterLength                         Tag = 0x4200d0
	TagCredential                            Tag = 0x420023
	TagCredentialType                        Tag = 0x420024
	TagCredentialValue                       Tag = 0x420025
	TagCriticalityIndicator                  Tag = 0x420026
	TagCryptographicAlgorithm                Tag = 0x420028
	TagCryptographicDomainParameters         Tag = 0x420029
	TagCryptographicLength                   Tag = 0x42002a
	TagCryptographicParameters               Tag = 0x42002b
	TagCryptographicUsageMask                Tag = 0x42002c
	TagCustomAttribute                       Tag = 0x42002d
	TagD                                     Tag = 0x42002e
	TagDRBGAlgorithm                         Tag = 0x4200db
	TagData                                  Tag = 0x4200c2
	TagDataLength                            Tag = 0x4200c4
	TagDeactivationDate                      Tag = 0x42002f
	TagDerivationData                        Tag = 0x420030
	TagDerivationMethod                      Tag = 0x420031
	TagDerivationParameters                  Tag = 0x420032
	TagDescription                           Tag = 0x4200fc
	TagDestroyAction                         Tag = 0x4200f3
	TagDestroyDate                           Tag = 0x420033
	TagDeviceIdentifier                      Tag = 0x4200a2
	TagDeviceSerialNumber                    Tag = 0x4200b0
	TagDigest                                Tag = 0x420034
	TagDigestValue                           Tag = 0x420035
	TagDigestedData                          Tag = 0x420107
	TagDigitalSignatureAlgorithm             Tag = 0x4200ae
	TagEncodingOption                        Tag = 0x4200a3
	TagEncryptionKeyInformation              Tag = 0x420036
	TagExtensionInformation                  Tag = 0x4200a4
	TagExtensionName                         Tag = 0x4200a5
	TagExtensionTag                          Tag = 0x4200a6
	TagExtensionType                         Tag = 0x4200a7
	TagExtractable                           Tag = 0x420122
	TagFIPS186Variation                      Tag = 0x4200dc
	TagFinalIndicator                        Tag = 0x4200d8
	TagFixedFieldLength                      Tag = 0x4200cf
	TagFresh                                 Tag = 0x4200a8
	TagG                                     Tag = 0x420037
	TagHashingAlgorithm                      Tag = 0x420038
	TagIVCounterNonce                        Tag = 0x42003d
	TagIVLength                              Tag = 0x4200cd
	TagInitIndicator                         Tag = 0x4200d7
	TagInitialCounterValue                   Tag = 0x4200d1
	TagInitialDate                           Tag = 0x420039
	TagInitializationVector                  Tag = 0x42003a
	TagInvocationFieldLength                 Tag = 0x4200d2
	TagIssuer                                Tag = 0x42003b
	TagIssuerAlternativeName                 Tag = 0x4200b1
	TagIssuerDistinguishedName               Tag = 0x4200b2
	TagIterationCount                        Tag = 0x42003c
	TagJ                                     Tag = 0x42003e
	TagKey                                   Tag = 0x42003f
	TagKeyBlock                              Tag = 0x420040
	TagKeyCompressionType                    Tag = 0x420041
	TagKeyFormatType                         Tag = 0x420042
	TagKeyMaterial                           Tag = 0x420043
	TagKeyPartIdentifier                     Tag = 0x420044
	TagKeyRoleType                           Tag = 0x420083
	TagKeyValue                              Tag = 0x420045
	TagKeyValueLocation                      Tag = 0x4200b8
	TagKeyValueLocationType                  Tag = 0x4200ba
	TagKeyValueLocationValue                 Tag = 0x4200b9
	TagKeyValuePresent                       Tag = 0x4200bb
	TagKeyWrapType                           Tag = 0x4200f8
	TagKeyWrappingData                       Tag = 0x420046
	TagKeyWrappingSpecification              Tag = 0x420047
	TagLastChangeDate                        Tag = 0x420048
	TagLeaseTime                             Tag = 0x420049
	TagLink                                  Tag = 0x42004a
	TagLinkType                              Tag = 0x42004b
	TagLinkedObjectIdentifier                Tag = 0x42004c
	TagLocatedItems                          Tag = 0x4200d5
	TagMACData                               Tag = 0x4200c6
	TagMACSignature                          Tag = 0x42004d
	TagMACSignatureKeyInformation            Tag = 0x42004e
	TagMachineIdentifier                     Tag = 0x4200a9
	TagMaskGenerator                         Tag = 0x420101
	TagMaskGeneratorHashingAlgorithm         Tag = 0x420102
	TagMaximumItems                          Tag = 0x42004f
	TagMaximumResponseSize                   Tag = 0x420050
	TagMediaIdentifier                       Tag = 0x4200aa
	TagMessageExtension                      Tag = 0x420051
	TagModulus                               Tag = 0x420052
	TagName                                  Tag = 0x420053
	TagNameType                              Tag = 0x420054
	TagNameValue                             Tag = 0x420055
	TagNetworkIdentifier                     Tag = 0x4200ab
	TagNeverExtractable                      Tag = 0x420123
	TagNonce                                 Tag = 0x4200c8
	TagNonceID                               Tag = 0x4200c9
	TagNonceValue                            Tag = 0x4200ca
	TagNone                                  Tag = 0x000000
	TagObjectGroup                           Tag = 0x420056
	TagObjectGroupMember                     Tag = 0x4200ac
	TagObjectType                            Tag = 0x420057
	TagOffset                                Tag = 0x420058
	TagOffsetItems                           Tag = 0x4200d4
	TagOpaqueDataType                        Tag = 0x420059
	TagOpaqueDataValue                       Tag = 0x42005a
	TagOpaqueObject                          Tag = 0x42005b
	TagOperation                             Tag = 0x42005c
	TagOperationPolicyName                   Tag = 0x42005d
	TagOriginalCreationDate                  Tag = 0x4200bc
	TagP                                     Tag = 0x42005e
	TagPGPKey                                Tag = 0x4200bd
	TagPGPKeyVersion                         Tag = 0x4200be
	TagPKCS_12FriendlyName                   Tag = 0x4200fb
	TagPSource                               Tag = 0x420103
	TagPaddingMethod                         Tag = 0x42005f
	TagPassword                              Tag = 0x4200a1
	TagPredictionResistance                  Tag = 0x4200dd
	TagPrimeExponentP                        Tag = 0x420060
	TagPrimeExponentQ                        Tag = 0x420061
	TagPrimeFieldSize                        Tag = 0x420062
	TagPrivateExponent                       Tag = 0x420063
	TagPrivateKey                            Tag = 0x420064
	TagPrivateKeyTemplateAttribute           Tag = 0x420065
	TagPrivateKeyUniqueIdentifier            Tag = 0x420066
	TagProcessStartDate                      Tag = 0x420067
	TagProfileInformation                    Tag = 0x4200eb
	TagProfileName                           Tag = 0x4200ec
	TagProtectStopDate                       Tag = 0x420068
	TagProtocolVersion                       Tag = 0x420069
	TagProtocolVersionMajor                  Tag = 0x42006a
	TagProtocolVersionMinor                  Tag = 0x42006b
	TagPublicExponent                        Tag = 0x42006c
	TagPublicKey                             Tag = 0x42006d
	TagPublicKeyTemplateAttribute            Tag = 0x42006e
	TagPublicKeyUniqueIdentifier             Tag = 0x42006f
	TagPutFunction                           Tag = 0x420070
	TagQ                                     Tag = 0x420071
	TagQString                               Tag = 0x420072
	TagQlength                               Tag = 0x420073
	TagQueryFunction                         Tag = 0x420074
	TagRNGAlgorithm                          Tag = 0x4200da
	TagRNGMode                               Tag = 0x4200f5
	TagRNGParameters                         Tag = 0x4200d9
	TagRandomIV                              Tag = 0x4200c5
	TagRandomNumberGenerator                 Tag = 0x4200de
	TagRecommendedCurve                      Tag = 0x420075
	TagReplaceExisting                       Tag = 0x420124
	TagReplacedUniqueIdentifier              Tag = 0x420076
	TagRequestHeader                         Tag = 0x420077
	TagRequestMessage                        Tag = 0x420078
	TagRequestPayload                        Tag = 0x420079
	TagResponseHeader                        Tag = 0x42007a
	TagResponseMessage                       Tag = 0x42007b
	TagResponsePayload                       Tag = 0x42007c
	TagResultMessage                         Tag = 0x42007d
	TagResultReason                          Tag = 0x42007e
	TagResultStatus                          Tag = 0x42007f
	TagRevocationMessage                     Tag = 0x420080
	TagRevocationReason                      Tag = 0x420081
	TagRevocationReasonCode                  Tag = 0x420082
	TagSalt                                  Tag = 0x420084
	TagSaltLength                            Tag = 0x420100
	TagSecretData                            Tag = 0x420085
	TagSecretDataType                        Tag = 0x420086
	TagSensitive                             Tag = 0x420120
	TagSerialNumber                          Tag = 0x420087
	TagServerCorrelationValue                Tag = 0x420106
	TagServerInformation                     Tag = 0x420088
	TagServerPort                            Tag = 0x4200ee
	TagServerURI                             Tag = 0x4200ed
	TagShreddingAlgorithm                    Tag = 0x4200f4
	TagSignatureData                         Tag = 0x4200c3
	TagSplitKey                              Tag = 0x420089
	TagSplitKeyMethod                        Tag = 0x42008a
	TagSplitKeyParts                         Tag = 0x42008b
	TagSplitKeyThreshold                     Tag = 0x42008c
	TagState                                 Tag = 0x42008d
	TagStorageStatusMask                     Tag = 0x42008e
	TagStreamingCapability                   Tag = 0x4200ef
	TagSubjectAlternativeName                Tag = 0x4200b3
	TagSubjectDistinguishedName              Tag = 0x4200b4
	TagSymmetricKey                          Tag = 0x42008f
	TagTagLength                             Tag = 0x4200ce
	TagTemplate                              Tag = 0x420090
	TagTemplateAttribute                     Tag = 0x420091
	TagTimeStamp                             Tag = 0x420092
	TagTrailerField                          Tag = 0x420104
	TagUniqueBatchItemID                     Tag = 0x420093
	TagUniqueIdentifier                      Tag = 0x420094
	TagUnwrapMode                            Tag = 0x4200f2
	TagUsageLimits                           Tag = 0x420095
	TagUsageLimitsCount                      Tag = 0x420096
	TagUsageLimitsTotal                      Tag = 0x420097
	TagUsageLimitsUnit                       Tag = 0x420098
	TagUsername                              Tag = 0x420099
	TagValidationAuthorityCountry            Tag = 0x4200e1
	TagValidationAuthorityType               Tag = 0x4200e0
	TagValidationAuthorityURI                Tag = 0x4200e2
	TagValidationCertificateIdentifier       Tag = 0x4200e7
	TagValidationCertificateURI              Tag = 0x4200e8
	TagValidationInformation                 Tag = 0x4200df
	TagValidationLevel                       Tag = 0x4200e6
	TagValidationProfile                     Tag = 0x4200ea
	TagValidationType                        Tag = 0x4200e5
	TagValidationVendorURI                   Tag = 0x4200e9
	TagValidationVersionMajor                Tag = 0x4200e3
	TagValidationVersionMinor                Tag = 0x4200e4
	TagValidityDate                          Tag = 0x42009a
	TagValidityIndicator                     Tag = 0x42009b
	TagVendorExtension                       Tag = 0x42009c
	TagVendorIdentification                  Tag = 0x42009d
	TagWrappingMethod                        Tag = 0x42009e
	TagX                                     Tag = 0x42009f
	TagX_509CertificateIdentifier            Tag = 0x4200b5
	TagX_509CertificateIssuer                Tag = 0x4200b6
	TagX_509CertificateSubject               Tag = 0x4200b7
	TagY                                     Tag = 0x4200a0
)

var _TagNameToValueMap = map[string]Tag{
	"ActivationDate":                        TagActivationDate,
	"AlternativeName":                       TagAlternativeName,
	"AlternativeNameType":                   TagAlternativeNameType,
	"AlternativeNameValue":                  TagAlternativeNameValue,
	"AlwaysSensitive":                       TagAlwaysSensitive,
	"ApplicationData":                       TagApplicationData,
	"ApplicationNamespace":                  TagApplicationNamespace,
	"ApplicationSpecificInformation":        TagApplicationSpecificInformation,
	"ArchiveDate":                           TagArchiveDate,
	"AsynchronousCapability":                TagAsynchronousCapability,
	"AsynchronousCorrelationValue":          TagAsynchronousCorrelationValue,
	"AsynchronousIndicator":                 TagAsynchronousIndicator,
	"AttestationAssertion":                  TagAttestationAssertion,
	"AttestationCapability":                 TagAttestationCapability,
	"AttestationCapableIndicator":           TagAttestationCapableIndicator,
	"AttestationMeasurement":                TagAttestationMeasurement,
	"AttestationType":                       TagAttestationType,
	"Attribute":                             TagAttribute,
	"AttributeIndex":                        TagAttributeIndex,
	"AttributeName":                         TagAttributeName,
	"AttributeValue":                        TagAttributeValue,
	"AuthenticatedEncryptionAdditionalData": TagAuthenticatedEncryptionAdditionalData,
	"AuthenticatedEncryptionTag":            TagAuthenticatedEncryptionTag,
	"Authentication":                        TagAuthentication,
	"BatchContinueCapability":               TagBatchContinueCapability,
	"BatchCount":                            TagBatchCount,
	"BatchErrorContinuationOption":          TagBatchErrorContinuationOption,
	"BatchItem":                             TagBatchItem,
	"BatchOrderOption":                      TagBatchOrderOption,
	"BatchUndoCapability":                   TagBatchUndoCapability,
	"BlockCipherMode":                       TagBlockCipherMode,
	"CRTCoefficient":                        TagCRTCoefficient,
	"CancellationResult":                    TagCancellationResult,
	"CapabilityInformation":                 TagCapabilityInformation,
	"Certificate":                           TagCertificate,
	"CertificateIdentifier":                 TagCertificateIdentifier,
	"CertificateIssuer":                     TagCertificateIssuer,
	"CertificateIssuerAlternativeName":      TagCertificateIssuerAlternativeName,
	"CertificateIssuerC":                    TagCertificateIssuerC,
	"CertificateIssuerCN":                   TagCertificateIssuerCN,
	"CertificateIssuerDC":                   TagCertificateIssuerDC,
	"CertificateIssuerDNQualifier":          TagCertificateIssuerDNQualifier,
	"CertificateIssuerDistinguishedName":    TagCertificateIssuerDistinguishedName,
	"CertificateIssuerEmail":                TagCertificateIssuerEmail,
	"CertificateIssuerL":                    TagCertificateIssuerL,
	"CertificateIssuerO":                    TagCertificateIssuerO,
	"CertificateIssuerOU":                   TagCertificateIssuerOU,
	"CertificateIssuerST":                   TagCertificateIssuerST,
	"CertificateIssuerSerialNumber":         TagCertificateIssuerSerialNumber,
	"CertificateIssuerTitle":                TagCertificateIssuerTitle,
	"CertificateIssuerUID":                  TagCertificateIssuerUID,
	"CertificateLength":                     TagCertificateLength,
	"CertificateRequest":                    TagCertificateRequest,
	"CertificateRequestType":                TagCertificateRequestType,
	"CertificateSerialNumber":               TagCertificateSerialNumber,
	"CertificateSubject":                    TagCertificateSubject,
	"CertificateSubjectAlternativeName":     TagCertificateSubjectAlternativeName,
	"CertificateSubjectC":                   TagCertificateSubjectC,
	"CertificateSubjectCN":                  TagCertificateSubjectCN,
	"CertificateSubjectDC":                  TagCertificateSubjectDC,
	"CertificateSubjectDNQualifier":         TagCertificateSubjectDNQualifier,
	"CertificateSubjectDistinguishedName":   TagCertificateSubjectDistinguishedName,
	"CertificateSubjectEmail":               TagCertificateSubjectEmail,
	"CertificateSubjectL":                   TagCertificateSubjectL,
	"CertificateSubjectO":                   TagCertificateSubjectO,
	"CertificateSubjectOU":                  TagCertificateSubjectOU,
	"CertificateSubjectST":                  TagCertificateSubjectST,
	"CertificateSubjectSerialNumber":        TagCertificateSubjectSerialNumber,
	"CertificateSubjectTitle":               TagCertificateSubjectTitle,
	"CertificateSubjectUID":                 TagCertificateSubjectUID,
	"CertificateType":                       TagCertificateType,
	"CertificateValue":                      TagCertificateValue,
	"ClientCorrelationValue":                TagClientCorrelationValue,
	"ClientRegistrationMethod":              TagClientRegistrationMethod,
	"Comment":                               TagComment,
	"CommonTemplateAttribute":               TagCommonTemplateAttribute,
	"CompromiseDate":                        TagCompromiseDate,
	"CompromiseOccurrenceDate":              TagCompromiseOccurrenceDate,
	"ContactInformation":                    TagContactInformation,
	"CorrelationValue":                      TagCorrelationValue,
	"CounterLength":                         TagCounterLength,
	"Credential":                            TagCredential,
	"CredentialType":                        TagCredentialType,
	"CredentialValue":                       TagCredentialValue,
	"CriticalityIndicator":                  TagCriticalityIndicator,
	"CryptographicAlgorithm":                TagCryptographicAlgorithm,
	"CryptographicDomainParameters":         TagCryptographicDomainParameters,
	"CryptographicLength":                   TagCryptographicLength,
	"CryptographicParameters":               TagCryptographicParameters,
	"CryptographicUsageMask":                TagCryptographicUsageMask,
	"CustomAttribute":                       TagCustomAttribute,
	"D":                                     TagD,
	"DRBGAlgorithm":                         TagDRBGAlgorithm,
	"Data":                                  TagData,
	"DataLength":                            TagDataLength,
	"DeactivationDate":                      TagDeactivationDate,
	"DerivationData":                        TagDerivationData,
	"DerivationMethod":                      TagDerivationMethod,
	"DerivationParameters":                  TagDerivationParameters,
	"Description":                           TagDescription,
	"DestroyAction":                         TagDestroyAction,
	"DestroyDate":                           TagDestroyDate,
	"DeviceIdentifier":                      TagDeviceIdentifier,
	"DeviceSerialNumber":                    TagDeviceSerialNumber,
	"Digest":                                TagDigest,
	"DigestValue":                           TagDigestValue,
	"DigestedData":                          TagDigestedData,
	"DigitalSignatureAlgorithm":             TagDigitalSignatureAlgorithm,
	"EncodingOption":                        TagEncodingOption,
	"EncryptionKeyInformation":              TagEncryptionKeyInformation,
	"ExtensionInformation":                  TagExtensionInformation,
	"ExtensionName":                         TagExtensionName,
	"ExtensionTag":                          TagExtensionTag,
	"ExtensionType":                         TagExtensionType,
	"Extractable":                           TagExtractable,
	"FIPS186Variation":                      TagFIPS186Variation,
	"FinalIndicator":                        TagFinalIndicator,
	"FixedFieldLength":                      TagFixedFieldLength,
	"Fresh":                                 TagFresh,
	"G":                                     TagG,
	"HashingAlgorithm":                      TagHashingAlgorithm,
	"IVCounterNonce":                        TagIVCounterNonce,
	"IVLength":                              TagIVLength,
	"InitIndicator":                         TagInitIndicator,
	"InitialCounterValue":                   TagInitialCounterValue,
	"InitialDate":                           TagInitialDate,
	"InitializationVector":                  TagInitializationVector,
	"InvocationFieldLength":                 TagInvocationFieldLength,
	"Issuer":                                TagIssuer,
	"IssuerAlternativeName":                 TagIssuerAlternativeName,
	"IssuerDistinguishedName":               TagIssuerDistinguishedName,
	"IterationCount":                        TagIterationCount,
	"J":                                     TagJ,
	"Key":                                   TagKey,
	"KeyBlock":                              TagKeyBlock,
	"KeyCompressionType":                    TagKeyCompressionType,
	"KeyFormatType":                         TagKeyFormatType,
	"KeyMaterial":                           TagKeyMaterial,
	"KeyPartIdentifier":                     TagKeyPartIdentifier,
	"KeyRoleType":                           TagKeyRoleType,
	"KeyValue":                              TagKeyValue,
	"KeyValueLocation":                      TagKeyValueLocation,
	"KeyValueLocationType":                  TagKeyValueLocationType,
	"KeyValueLocationValue":                 TagKeyValueLocationValue,
	"KeyValuePresent":                       TagKeyValuePresent,
	"KeyWrapType":                           TagKeyWrapType,
	"KeyWrappingData":                       TagKeyWrappingData,
	"KeyWrappingSpecification":              TagKeyWrappingSpecification,
	"LastChangeDate":                        TagLastChangeDate,
	"LeaseTime":                             TagLeaseTime,
	"Link":                                  TagLink,
	"LinkType":                              TagLinkType,
	"LinkedObjectIdentifier":                TagLinkedObjectIdentifier,
	"LocatedItems":                          TagLocatedItems,
	"MACData":                               TagMACData,
	"MACSignature":                          TagMACSignature,
	"MACSignatureKeyInformation":            TagMACSignatureKeyInformation,
	"MachineIdentifier":                     TagMachineIdentifier,
	"MaskGenerator":                         TagMaskGenerator,
	"MaskGeneratorHashingAlgorithm":         TagMaskGeneratorHashingAlgorithm,
	"MaximumItems":                          TagMaximumItems,
	"MaximumResponseSize":                   TagMaximumResponseSize,
	"MediaIdentifier":                       TagMediaIdentifier,
	"MessageExtension":                      TagMessageExtension,
	"Modulus":                               TagModulus,
	"Name":                                  TagName,
	"NameType":                              TagNameType,
	"NameValue":                             TagNameValue,
	"NetworkIdentifier":                     TagNetworkIdentifier,
	"NeverExtractable":                      TagNeverExtractable,
	"Nonce":                                 TagNonce,
	"NonceID":                               TagNonceID,
	"NonceValue":                            TagNonceValue,
	"None":                                  TagNone,
	"ObjectGroup":                           TagObjectGroup,
	"ObjectGroupMember":                     TagObjectGroupMember,
	"ObjectType":                            TagObjectType,
	"Offset":                                TagOffset,
	"OffsetItems":                           TagOffsetItems,
	"OpaqueDataType":                        TagOpaqueDataType,
	"OpaqueDataValue":                       TagOpaqueDataValue,
	"OpaqueObject":                          TagOpaqueObject,
	"Operation":                             TagOperation,
	"OperationPolicyName":                   TagOperationPolicyName,
	"OriginalCreationDate":                  TagOriginalCreationDate,
	"P":                                     TagP,
	"PGPKey":                                TagPGPKey,
	"PGPKeyVersion":                         TagPGPKeyVersion,
	"PKCS_12FriendlyName":                   TagPKCS_12FriendlyName,
	"PSource":                               TagPSource,
	"PaddingMethod":                         TagPaddingMethod,
	"Password":                              TagPassword,
	"PredictionResistance":                  TagPredictionResistance,
	"PrimeExponentP":                        TagPrimeExponentP,
	"PrimeExponentQ":                        TagPrimeExponentQ,
	"PrimeFieldSize":                        TagPrimeFieldSize,
	"PrivateExponent":                       TagPrivateExponent,
	"PrivateKey":                            TagPrivateKey,
	"PrivateKeyTemplateAttribute":           TagPrivateKeyTemplateAttribute,
	"PrivateKeyUniqueIdentifier":            TagPrivateKeyUniqueIdentifier,
	"ProcessStartDate":                      TagProcessStartDate,
	"ProfileInformation":                    TagProfileInformation,
	"ProfileName":                           TagProfileName,
	"ProtectStopDate":                       TagProtectStopDate,
	"ProtocolVersion":                       TagProtocolVersion,
	"ProtocolVersionMajor":                  TagProtocolVersionMajor,
	"ProtocolVersionMinor":                  TagProtocolVersionMinor,
	"PublicExponent":                        TagPublicExponent,
	"PublicKey":                             TagPublicKey,
	"PublicKeyTemplateAttribute":            TagPublicKeyTemplateAttribute,
	"PublicKeyUniqueIdentifier":             TagPublicKeyUniqueIdentifier,
	"PutFunction":                           TagPutFunction,
	"Q":                                     TagQ,
	"QString":                               TagQString,
	"Qlength":                               TagQlength,
	"QueryFunction":                         TagQueryFunction,
	"RNGAlgorithm":                          TagRNGAlgorithm,
	"RNGMode":                               TagRNGMode,
	"RNGParameters":                         TagRNGParameters,
	"RandomIV":                              TagRandomIV,
	"RandomNumberGenerator":                 TagRandomNumberGenerator,
	"RecommendedCurve":                      TagRecommendedCurve,
	"ReplaceExisting":                       TagReplaceExisting,
	"ReplacedUniqueIdentifier":              TagReplacedUniqueIdentifier,
	"RequestHeader":                         TagRequestHeader,
	"RequestMessage":                        TagRequestMessage,
	"RequestPayload":                        TagRequestPayload,
	"ResponseHeader":                        TagResponseHeader,
	"ResponseMessage":                       TagResponseMessage,
	"ResponsePayload":                       TagResponsePayload,
	"ResultMessage":                         TagResultMessage,
	"ResultReason":                          TagResultReason,
	"ResultStatus":                          TagResultStatus,
	"RevocationMessage":                     TagRevocationMessage,
	"RevocationReason":                      TagRevocationReason,
	"RevocationReasonCode":                  TagRevocationReasonCode,
	"Salt":                                  TagSalt,
	"SaltLength":                            TagSaltLength,
	"SecretData":                            TagSecretData,
	"SecretDataType":                        TagSecretDataType,
	"Sensitive":                             TagSensitive,
	"SerialNumber":                          TagSerialNumber,
	"ServerCorrelationValue":                TagServerCorrelationValue,
	"ServerInformation":                     TagServerInformation,
	"ServerPort":                            TagServerPort,
	"ServerURI":                             TagServerURI,
	"ShreddingAlgorithm":                    TagShreddingAlgorithm,
	"SignatureData":                         TagSignatureData,
	"SplitKey":                              TagSplitKey,
	"SplitKeyMethod":                        TagSplitKeyMethod,
	"SplitKeyParts":                         TagSplitKeyParts,
	"SplitKeyThreshold":                     TagSplitKeyThreshold,
	"State":                                 TagState,
	"StorageStatusMask":                     TagStorageStatusMask,
	"StreamingCapability":                   TagStreamingCapability,
	"SubjectAlternativeName":                TagSubjectAlternativeName,
	"SubjectDistinguishedName":              TagSubjectDistinguishedName,
	"SymmetricKey":                          TagSymmetricKey,
	"TagLength":                             TagTagLength,
	"Template":                              TagTemplate,
	"TemplateAttribute":                     TagTemplateAttribute,
	"TimeStamp":                             TagTimeStamp,
	"TrailerField":                          TagTrailerField,
	"UniqueBatchItemID":                     TagUniqueBatchItemID,
	"UniqueIdentifier":                      TagUniqueIdentifier,
	"UnwrapMode":                            TagUnwrapMode,
	"UsageLimits":                           TagUsageLimits,
	"UsageLimitsCount":                      TagUsageLimitsCount,
	"UsageLimitsTotal":                      TagUsageLimitsTotal,
	"UsageLimitsUnit":                       TagUsageLimitsUnit,
	"Username":                              TagUsername,
	"ValidationAuthorityCountry":            TagValidationAuthorityCountry,
	"ValidationAuthorityType":               TagValidationAuthorityType,
	"ValidationAuthorityURI":                TagValidationAuthorityURI,
	"ValidationCertificateIdentifier":       TagValidationCertificateIdentifier,
	"ValidationCertificateURI":              TagValidationCertificateURI,
	"ValidationInformation":                 TagValidationInformation,
	"ValidationLevel":                       TagValidationLevel,
	"ValidationProfile":                     TagValidationProfile,
	"ValidationType":                        TagValidationType,
	"ValidationVendorURI":                   TagValidationVendorURI,
	"ValidationVersionMajor":                TagValidationVersionMajor,
	"ValidationVersionMinor":                TagValidationVersionMinor,
	"ValidityDate":                          TagValidityDate,
	"ValidityIndicator":                     TagValidityIndicator,
	"VendorExtension":                       TagVendorExtension,
	"VendorIdentification":                  TagVendorIdentification,
	"WrappingMethod":                        TagWrappingMethod,
	"X":                                     TagX,
	"X_509CertificateIdentifier":            TagX_509CertificateIdentifier,
	"X_509CertificateIssuer":                TagX_509CertificateIssuer,
	"X_509CertificateSubject":               TagX_509CertificateSubject,
	"Y":                                     TagY,
}

var _TagValueToNameMap = map[Tag]string{
	TagActivationDate:                        "ActivationDate",
	TagAlternativeName:                       "AlternativeName",
	TagAlternativeNameType:                   "AlternativeNameType",
	TagAlternativeNameValue:                  "AlternativeNameValue",
	TagAlwaysSensitive:                       "AlwaysSensitive",
	TagApplicationData:                       "ApplicationData",
	TagApplicationNamespace:                  "ApplicationNamespace",
	TagApplicationSpecificInformation:        "ApplicationSpecificInformation",
	TagArchiveDate:                           "ArchiveDate",
	TagAsynchronousCapability:                "AsynchronousCapability",
	TagAsynchronousCorrelationValue:          "AsynchronousCorrelationValue",
	TagAsynchronousIndicator:                 "AsynchronousIndicator",
	TagAttestationAssertion:                  "AttestationAssertion",
	TagAttestationCapability:                 "AttestationCapability",
	TagAttestationCapableIndicator:           "AttestationCapableIndicator",
	TagAttestationMeasurement:                "AttestationMeasurement",
	TagAttestationType:                       "AttestationType",
	TagAttribute:                             "Attribute",
	TagAttributeIndex:                        "AttributeIndex",
	TagAttributeName:                         "AttributeName",
	TagAttributeValue:                        "AttributeValue",
	TagAuthenticatedEncryptionAdditionalData: "AuthenticatedEncryptionAdditionalData",
	TagAuthenticatedEncryptionTag:            "AuthenticatedEncryptionTag",
	TagAuthentication:                        "Authentication",
	TagBatchContinueCapability:               "BatchContinueCapability",
	TagBatchCount:                            "BatchCount",
	TagBatchErrorContinuationOption:          "BatchErrorContinuationOption",
	TagBatchItem:                             "BatchItem",
	TagBatchOrderOption:                      "BatchOrderOption",
	TagBatchUndoCapability:                   "BatchUndoCapability",
	TagBlockCipherMode:                       "BlockCipherMode",
	TagCRTCoefficient:                        "CRTCoefficient",
	TagCancellationResult:                    "CancellationResult",
	TagCapabilityInformation:                 "CapabilityInformation",
	TagCertificate:                           "Certificate",
	TagCertificateIdentifier:                 "CertificateIdentifier",
	TagCertificateIssuer:                     "CertificateIssuer",
	TagCertificateIssuerAlternativeName:      "CertificateIssuerAlternativeName",
	TagCertificateIssuerC:                    "CertificateIssuerC",
	TagCertificateIssuerCN:                   "CertificateIssuerCN",
	TagCertificateIssuerDC:                   "CertificateIssuerDC",
	TagCertificateIssuerDNQualifier:          "CertificateIssuerDNQualifier",
	TagCertificateIssuerDistinguishedName:    "CertificateIssuerDistinguishedName",
	TagCertificateIssuerEmail:                "CertificateIssuerEmail",
	TagCertificateIssuerL:                    "CertificateIssuerL",
	TagCertificateIssuerO:                    "CertificateIssuerO",
	TagCertificateIssuerOU:                   "CertificateIssuerOU",
	TagCertificateIssuerST:                   "CertificateIssuerST",
	TagCertificateIssuerSerialNumber:         "CertificateIssuerSerialNumber",
	TagCertificateIssuerTitle:                "CertificateIssuerTitle",
	TagCertificateIssuerUID:                  "CertificateIssuerUID",
	TagCertificateLength:                     "CertificateLength",
	TagCertificateRequest:                    "CertificateRequest",
	TagCertificateRequestType:                "CertificateRequestType",
	TagCertificateSerialNumber:               "CertificateSerialNumber",
	TagCertificateSubject:                    "CertificateSubject",
	TagCertificateSubjectAlternativeName:     "CertificateSubjectAlternativeName",
	TagCertificateSubjectC:                   "CertificateSubjectC",
	TagCertificateSubjectCN:                  "CertificateSubjectCN",
	TagCertificateSubjectDC:                  "CertificateSubjectDC",
	TagCertificateSubjectDNQualifier:         "CertificateSubjectDNQualifier",
	TagCertificateSubjectDistinguishedName:   "CertificateSubjectDistinguishedName",
	TagCertificateSubjectEmail:               "CertificateSubjectEmail",
	TagCertificateSubjectL:                   "CertificateSubjectL",
	TagCertificateSubjectO:                   "CertificateSubjectO",
	TagCertificateSubjectOU:                  "CertificateSubjectOU",
	TagCertificateSubjectST:                  "CertificateSubjectST",
	TagCertificateSubjectSerialNumber:        "CertificateSubjectSerialNumber",
	TagCertificateSubjectTitle:               "CertificateSubjectTitle",
	TagCertificateSubjectUID:                 "CertificateSubjectUID",
	TagCertificateType:                       "CertificateType",
	TagCertificateValue:                      "CertificateValue",
	TagClientCorrelationValue:                "ClientCorrelationValue",
	TagClientRegistrationMethod:              "ClientRegistrationMethod",
	TagComment:                               "Comment",
	TagCommonTemplateAttribute:               "CommonTemplateAttribute",
	TagCompromiseDate:                        "CompromiseDate",
	TagCompromiseOccurrenceDate:              "CompromiseOccurrenceDate",
	TagContactInformation:                    "ContactInformation",
	TagCorrelationValue:                      "CorrelationValue",
	TagCounterLength:                         "CounterLength",
	TagCredential:                            "Credential",
	TagCredentialType:                        "CredentialType",
	TagCredentialValue:                       "CredentialValue",
	TagCriticalityIndicator:                  "CriticalityIndicator",
	TagCryptographicAlgorithm:                "CryptographicAlgorithm",
	TagCryptographicDomainParameters:         "CryptographicDomainParameters",
	TagCryptographicLength:                   "CryptographicLength",
	TagCryptographicParameters:               "CryptographicParameters",
	TagCryptographicUsageMask:                "CryptographicUsageMask",
	TagCustomAttribute:                       "CustomAttribute",
	TagD:                                     "D",
	TagDRBGAlgorithm:                         "DRBGAlgorithm",
	TagData:                                  "Data",
	TagDataLength:                            "DataLength",
	TagDeactivationDate:                      "DeactivationDate",
	TagDerivationData:                        "DerivationData",
	TagDerivationMethod:                      "DerivationMethod",
	TagDerivationParameters:                  "DerivationParameters",
	TagDescription:                           "Description",
	TagDestroyAction:                         "DestroyAction",
	TagDestroyDate:                           "DestroyDate",
	TagDeviceIdentifier:                      "DeviceIdentifier",
	TagDeviceSerialNumber:                    "DeviceSerialNumber",
	TagDigest:                                "Digest",
	TagDigestValue:                           "DigestValue",
	TagDigestedData:                          "DigestedData",
	TagDigitalSignatureAlgorithm:             "DigitalSignatureAlgorithm",
	TagEncodingOption:                        "EncodingOption",
	TagEncryptionKeyInformation:              "EncryptionKeyInformation",
	TagExtensionInformation:                  "ExtensionInformation",
	TagExtensionName:                         "ExtensionName",
	TagExtensionTag:                          "ExtensionTag",
	TagExtensionType:                         "ExtensionType",
	TagExtractable:                           "Extractable",
	TagFIPS186Variation:                      "FIPS186Variation",
	TagFinalIndicator:                        "FinalIndicator",
	TagFixedFieldLength:                      "FixedFieldLength",
	TagFresh:                                 "Fresh",
	TagG:                                     "G",
	TagHashingAlgorithm:                      "HashingAlgorithm",
	TagIVCounterNonce:                        "IVCounterNonce",
	TagIVLength:                              "IVLength",
	TagInitIndicator:                         "InitIndicator",
	TagInitialCounterValue:                   "InitialCounterValue",
	TagInitialDate:                           "InitialDate",
	TagInitializationVector:                  "InitializationVector",
	TagInvocationFieldLength:                 "InvocationFieldLength",
	TagIssuer:                                "Issuer",
	TagIssuerAlternativeName:                 "IssuerAlternativeName",
	TagIssuerDistinguishedName:               "IssuerDistinguishedName",
	TagIterationCount:                        "IterationCount",
	TagJ:                                     "J",
	TagKey:                                   "Key",
	TagKeyBlock:                              "KeyBlock",
	TagKeyCompressionType:                    "KeyCompressionType",
	TagKeyFormatType:                         "KeyFormatType",
	TagKeyMaterial:                           "KeyMaterial",
	TagKeyPartIdentifier:                     "KeyPartIdentifier",
	TagKeyRoleType:                           "KeyRoleType",
	TagKeyValue:                              "KeyValue",
	TagKeyValueLocation:                      "KeyValueLocation",
	TagKeyValueLocationType:                  "KeyValueLocationType",
	TagKeyValueLocationValue:                 "KeyValueLocationValue",
	TagKeyValuePresent:                       "KeyValuePresent",
	TagKeyWrapType:                           "KeyWrapType",
	TagKeyWrappingData:                       "KeyWrappingData",
	TagKeyWrappingSpecification:              "KeyWrappingSpecification",
	TagLastChangeDate:                        "LastChangeDate",
	TagLeaseTime:                             "LeaseTime",
	TagLink:                                  "Link",
	TagLinkType:                              "LinkType",
	TagLinkedObjectIdentifier:                "LinkedObjectIdentifier",
	TagLocatedItems:                          "LocatedItems",
	TagMACData:                               "MACData",
	TagMACSignature:                          "MACSignature",
	TagMACSignatureKeyInformation:            "MACSignatureKeyInformation",
	TagMachineIdentifier:                     "MachineIdentifier",
	TagMaskGenerator:                         "MaskGenerator",
	TagMaskGeneratorHashingAlgorithm:         "MaskGeneratorHashingAlgorithm",
	TagMaximumItems:                          "MaximumItems",
	TagMaximumResponseSize:                   "MaximumResponseSize",
	TagMediaIdentifier:                       "MediaIdentifier",
	TagMessageExtension:                      "MessageExtension",
	TagModulus:                               "Modulus",
	TagName:                                  "Name",
	TagNameType:                              "NameType",
	TagNameValue:                             "NameValue",
	TagNetworkIdentifier:                     "NetworkIdentifier",
	TagNeverExtractable:                      "NeverExtractable",
	TagNonce:                                 "Nonce",
	TagNonceID:                               "NonceID",
	TagNonceValue:                            "NonceValue",
	TagNone:                                  "None",
	TagObjectGroup:                           "ObjectGroup",
	TagObjectGroupMember:                     "ObjectGroupMember",
	TagObjectType:                            "ObjectType",
	TagOffset:                                "Offset",
	TagOffsetItems:                           "OffsetItems",
	TagOpaqueDataType:                        "OpaqueDataType",
	TagOpaqueDataValue:                       "OpaqueDataValue",
	TagOpaqueObject:                          "OpaqueObject",
	TagOperation:                             "Operation",
	TagOperationPolicyName:                   "OperationPolicyName",
	TagOriginalCreationDate:                  "OriginalCreationDate",
	TagP:                                     "P",
	TagPGPKey:                                "PGPKey",
	TagPGPKeyVersion:                         "PGPKeyVersion",
	TagPKCS_12FriendlyName:                   "PKCS_12FriendlyName",
	TagPSource:                               "PSource",
	TagPaddingMethod:                         "PaddingMethod",
	TagPassword:                              "Password",
	TagPredictionResistance:                  "PredictionResistance",
	TagPrimeExponentP:                        "PrimeExponentP",
	TagPrimeExponentQ:                        "PrimeExponentQ",
	TagPrimeFieldSize:                        "PrimeFieldSize",
	TagPrivateExponent:                       "PrivateExponent",
	TagPrivateKey:                            "PrivateKey",
	TagPrivateKeyTemplateAttribute:           "PrivateKeyTemplateAttribute",
	TagPrivateKeyUniqueIdentifier:            "PrivateKeyUniqueIdentifier",
	TagProcessStartDate:                      "ProcessStartDate",
	TagProfileInformation:                    "ProfileInformation",
	TagProfileName:                           "ProfileName",
	TagProtectStopDate:                       "ProtectStopDate",
	TagProtocolVersion:                       "ProtocolVersion",
	TagProtocolVersionMajor:                  "ProtocolVersionMajor",
	TagProtocolVersionMinor:                  "ProtocolVersionMinor",
	TagPublicExponent:                        "PublicExponent",
	TagPublicKey:                             "PublicKey",
	TagPublicKeyTemplateAttribute:            "PublicKeyTemplateAttribute",
	TagPublicKeyUniqueIdentifier:             "PublicKeyUniqueIdentifier",
	TagPutFunction:                           "PutFunction",
	TagQ:                                     "Q",
	TagQString:                               "QString",
	TagQlength:                               "Qlength",
	TagQueryFunction:                         "QueryFunction",
	TagRNGAlgorithm:                          "RNGAlgorithm",
	TagRNGMode:                               "RNGMode",
	TagRNGParameters:                         "RNGParameters",
	TagRandomIV:                              "RandomIV",
	TagRandomNumberGenerator:                 "RandomNumberGenerator",
	TagRecommendedCurve:                      "RecommendedCurve",
	TagReplaceExisting:                       "ReplaceExisting",
	TagReplacedUniqueIdentifier:              "ReplacedUniqueIdentifier",
	TagRequestHeader:                         "RequestHeader",
	TagRequestMessage:                        "RequestMessage",
	TagRequestPayload:                        "RequestPayload",
	TagResponseHeader:                        "ResponseHeader",
	TagResponseMessage:                       "ResponseMessage",
	TagResponsePayload:                       "ResponsePayload",
	TagResultMessage:                         "ResultMessage",
	TagResultReason:                          "ResultReason",
	TagResultStatus:                          "ResultStatus",
	TagRevocationMessage:                     "RevocationMessage",
	TagRevocationReason:                      "RevocationReason",
	TagRevocationReasonCode:                  "RevocationReasonCode",
	TagSalt:                                  "Salt",
	TagSaltLength:                            "SaltLength",
	TagSecretData:                            "SecretData",
	TagSecretDataType:                        "SecretDataType",
	TagSensitive:                             "Sensitive",
	TagSerialNumber:                          "SerialNumber",
	TagServerCorrelationValue:                "ServerCorrelationValue",
	TagServerInformation:                     "ServerInformation",
	TagServerPort:                            "ServerPort",
	TagServerURI:                             "ServerURI",
	TagShreddingAlgorithm:                    "ShreddingAlgorithm",
	TagSignatureData:                         "SignatureData",
	TagSplitKey:                              "SplitKey",
	TagSplitKeyMethod:                        "SplitKeyMethod",
	TagSplitKeyParts:                         "SplitKeyParts",
	TagSplitKeyThreshold:                     "SplitKeyThreshold",
	TagState:                                 "State",
	TagStorageStatusMask:                     "StorageStatusMask",
	TagStreamingCapability:                   "StreamingCapability",
	TagSubjectAlternativeName:                "SubjectAlternativeName",
	TagSubjectDistinguishedName:              "SubjectDistinguishedName",
	TagSymmetricKey:                          "SymmetricKey",
	TagTagLength:                             "TagLength",
	TagTemplate:                              "Template",
	TagTemplateAttribute:                     "TemplateAttribute",
	TagTimeStamp:                             "TimeStamp",
	TagTrailerField:                          "TrailerField",
	TagUniqueBatchItemID:                     "UniqueBatchItemID",
	TagUniqueIdentifier:                      "UniqueIdentifier",
	TagUnwrapMode:                            "UnwrapMode",
	TagUsageLimits:                           "UsageLimits",
	TagUsageLimitsCount:                      "UsageLimitsCount",
	TagUsageLimitsTotal:                      "UsageLimitsTotal",
	TagUsageLimitsUnit:                       "UsageLimitsUnit",
	TagUsername:                              "Username",
	TagValidationAuthorityCountry:            "ValidationAuthorityCountry",
	TagValidationAuthorityType:               "ValidationAuthorityType",
	TagValidationAuthorityURI:                "ValidationAuthorityURI",
	TagValidationCertificateIdentifier:       "ValidationCertificateIdentifier",
	TagValidationCertificateURI:              "ValidationCertificateURI",
	TagValidationInformation:                 "ValidationInformation",
	TagValidationLevel:                       "ValidationLevel",
	TagValidationProfile:                     "ValidationProfile",
	TagValidationType:                        "ValidationType",
	TagValidationVendorURI:                   "ValidationVendorURI",
	TagValidationVersionMajor:                "ValidationVersionMajor",
	TagValidationVersionMinor:                "ValidationVersionMinor",
	TagValidityDate:                          "ValidityDate",
	TagValidityIndicator:                     "ValidityIndicator",
	TagVendorExtension:                       "VendorExtension",
	TagVendorIdentification:                  "VendorIdentification",
	TagWrappingMethod:                        "WrappingMethod",
	TagX:                                     "X",
	TagX_509CertificateIdentifier:            "X_509CertificateIdentifier",
	TagX_509CertificateIssuer:                "X_509CertificateIssuer",
	TagX_509CertificateSubject:               "X_509CertificateSubject",
	TagY:                                     "Y",
}

// Code generated by "kmipenums "; DO NOT EDIT.

// Credential Type Enumeration
// 9.1.3.2.1
type CredentialType uint32

const (
	CredentialTypeAttestation         CredentialType = 0x00000003
	CredentialTypeDevice              CredentialType = 0x00000002
	CredentialTypeUsernameAndPassword CredentialType = 0x00000001
)

var _CredentialTypeNameToValueMap = map[string]CredentialType{
	"Attestation":         CredentialTypeAttestation,
	"Device":              CredentialTypeDevice,
	"UsernameAndPassword": CredentialTypeUsernameAndPassword,
}

var _CredentialTypeValueToNameMap = map[CredentialType]string{
	CredentialTypeAttestation:         "Attestation",
	CredentialTypeDevice:              "Device",
	CredentialTypeUsernameAndPassword: "UsernameAndPassword",
}

func (c CredentialType) String() string {
	if s, ok := _CredentialTypeValueToNameMap[c]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", c)
}

func ParseCredentialType(s string) (CredentialType, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return CredentialType(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _CredentialTypeNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v CredentialType
		return v, fmt.Errorf("%s is not a valid CredentialType", s)
	}
}

func (c CredentialType) MarshalText() (text []byte, err error) {
	return []byte(c.String()), nil
}

func (c *CredentialType) UnmarshalText(text []byte) (err error) {
	*c, err = ParseCredentialType(string(text))
	return
}

func (c CredentialType) MarshalTTLVEnum() uint32 {
	return uint32(c)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Key Compression Type Enumeration
// 9.1.3.2.2
type KeyCompressionType uint32

const (
	KeyCompressionTypeECPublicKeyTypeUncompressed         KeyCompressionType = 0x00000001
	KeyCompressionTypeECPublicKeyTypeX9_62CompressedChar2 KeyCompressionType = 0x00000003
	KeyCompressionTypeECPublicKeyTypeX9_62CompressedPrime KeyCompressionType = 0x00000002
	KeyCompressionTypeECPublicKeyTypeX9_62Hybrid          KeyCompressionType = 0x00000004
)

var _KeyCompressionTypeNameToValueMap = map[string]KeyCompressionType{
	"ECPublicKeyTypeUncompressed":         KeyCompressionTypeECPublicKeyTypeUncompressed,
	"ECPublicKeyTypeX9_62CompressedChar2": KeyCompressionTypeECPublicKeyTypeX9_62CompressedChar2,
	"ECPublicKeyTypeX9_62CompressedPrime": KeyCompressionTypeECPublicKeyTypeX9_62CompressedPrime,
	"ECPublicKeyTypeX9_62Hybrid":          KeyCompressionTypeECPublicKeyTypeX9_62Hybrid,
}

var _KeyCompressionTypeValueToNameMap = map[KeyCompressionType]string{
	KeyCompressionTypeECPublicKeyTypeUncompressed:         "ECPublicKeyTypeUncompressed",
	KeyCompressionTypeECPublicKeyTypeX9_62CompressedChar2: "ECPublicKeyTypeX9_62CompressedChar2",
	KeyCompressionTypeECPublicKeyTypeX9_62CompressedPrime: "ECPublicKeyTypeX9_62CompressedPrime",
	KeyCompressionTypeECPublicKeyTypeX9_62Hybrid:          "ECPublicKeyTypeX9_62Hybrid",
}

func (k KeyCompressionType) String() string {
	if s, ok := _KeyCompressionTypeValueToNameMap[k]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", k)
}

func ParseKeyCompressionType(s string) (KeyCompressionType, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return KeyCompressionType(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _KeyCompressionTypeNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v KeyCompressionType
		return v, fmt.Errorf("%s is not a valid KeyCompressionType", s)
	}
}

func (k KeyCompressionType) MarshalText() (text []byte, err error) {
	return []byte(k.String()), nil
}

func (k *KeyCompressionType) UnmarshalText(text []byte) (err error) {
	*k, err = ParseKeyCompressionType(string(text))
	return
}

func (k KeyCompressionType) MarshalTTLVEnum() uint32 {
	return uint32(k)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Key Format Type Enumeration
// 9.1.3.2.3
type KeyFormatType uint32

const (
	KeyFormatTypeECPrivateKey               KeyFormatType = 0x00000006
	KeyFormatTypeOpaque                     KeyFormatType = 0x00000002
	KeyFormatTypePKCS_1                     KeyFormatType = 0x00000003
	KeyFormatTypePKCS_12                    KeyFormatType = 0x00000016
	KeyFormatTypePKCS_8                     KeyFormatType = 0x00000004
	KeyFormatTypeRaw                        KeyFormatType = 0x00000001
	KeyFormatTypeTransparentDHPrivateKey    KeyFormatType = 0x0000000c
	KeyFormatTypeTransparentDHPublicKey     KeyFormatType = 0x0000000d
	KeyFormatTypeTransparentDSAPrivateKey   KeyFormatType = 0x00000008
	KeyFormatTypeTransparentDSAPublicKey    KeyFormatType = 0x00000009
	KeyFormatTypeTransparentECDHPrivateKey  KeyFormatType = 0x00000010
	KeyFormatTypeTransparentECDHPublicKey   KeyFormatType = 0x00000011
	KeyFormatTypeTransparentECDSAPrivateKey KeyFormatType = 0x0000000e
	KeyFormatTypeTransparentECDSAPublicKey  KeyFormatType = 0x0000000f
	KeyFormatTypeTransparentECMQVPrivateKey KeyFormatType = 0x00000012
	KeyFormatTypeTransparentECMQVPublicKey  KeyFormatType = 0x00000013
	KeyFormatTypeTransparentECPrivateKey    KeyFormatType = 0x00000014
	KeyFormatTypeTransparentECPublicKey     KeyFormatType = 0x00000015
	KeyFormatTypeTransparentRSAPrivateKey   KeyFormatType = 0x0000000a
	KeyFormatTypeTransparentRSAPublicKey    KeyFormatType = 0x0000000b
	KeyFormatTypeTransparentSymmetricKey    KeyFormatType = 0x00000007
	KeyFormatTypeX_509                      KeyFormatType = 0x00000005
)

var _KeyFormatTypeNameToValueMap = map[string]KeyFormatType{
	"ECPrivateKey":               KeyFormatTypeECPrivateKey,
	"Opaque":                     KeyFormatTypeOpaque,
	"PKCS_1":                     KeyFormatTypePKCS_1,
	"PKCS_12":                    KeyFormatTypePKCS_12,
	"PKCS_8":                     KeyFormatTypePKCS_8,
	"Raw":                        KeyFormatTypeRaw,
	"TransparentDHPrivateKey":    KeyFormatTypeTransparentDHPrivateKey,
	"TransparentDHPublicKey":     KeyFormatTypeTransparentDHPublicKey,
	"TransparentDSAPrivateKey":   KeyFormatTypeTransparentDSAPrivateKey,
	"TransparentDSAPublicKey":    KeyFormatTypeTransparentDSAPublicKey,
	"TransparentECDHPrivateKey":  KeyFormatTypeTransparentECDHPrivateKey,
	"TransparentECDHPublicKey":   KeyFormatTypeTransparentECDHPublicKey,
	"TransparentECDSAPrivateKey": KeyFormatTypeTransparentECDSAPrivateKey,
	"TransparentECDSAPublicKey":  KeyFormatTypeTransparentECDSAPublicKey,
	"TransparentECMQVPrivateKey": KeyFormatTypeTransparentECMQVPrivateKey,
	"TransparentECMQVPublicKey":  KeyFormatTypeTransparentECMQVPublicKey,
	"TransparentECPrivateKey":    KeyFormatTypeTransparentECPrivateKey,
	"TransparentECPublicKey":     KeyFormatTypeTransparentECPublicKey,
	"TransparentRSAPrivateKey":   KeyFormatTypeTransparentRSAPrivateKey,
	"TransparentRSAPublicKey":    KeyFormatTypeTransparentRSAPublicKey,
	"TransparentSymmetricKey":    KeyFormatTypeTransparentSymmetricKey,
	"X_509":                      KeyFormatTypeX_509,
}

var _KeyFormatTypeValueToNameMap = map[KeyFormatType]string{
	KeyFormatTypeECPrivateKey:               "ECPrivateKey",
	KeyFormatTypeOpaque:                     "Opaque",
	KeyFormatTypePKCS_1:                     "PKCS_1",
	KeyFormatTypePKCS_12:                    "PKCS_12",
	KeyFormatTypePKCS_8:                     "PKCS_8",
	KeyFormatTypeRaw:                        "Raw",
	KeyFormatTypeTransparentDHPrivateKey:    "TransparentDHPrivateKey",
	KeyFormatTypeTransparentDHPublicKey:     "TransparentDHPublicKey",
	KeyFormatTypeTransparentDSAPrivateKey:   "TransparentDSAPrivateKey",
	KeyFormatTypeTransparentDSAPublicKey:    "TransparentDSAPublicKey",
	KeyFormatTypeTransparentECDHPrivateKey:  "TransparentECDHPrivateKey",
	KeyFormatTypeTransparentECDHPublicKey:   "TransparentECDHPublicKey",
	KeyFormatTypeTransparentECDSAPrivateKey: "TransparentECDSAPrivateKey",
	KeyFormatTypeTransparentECDSAPublicKey:  "TransparentECDSAPublicKey",
	KeyFormatTypeTransparentECMQVPrivateKey: "TransparentECMQVPrivateKey",
	KeyFormatTypeTransparentECMQVPublicKey:  "TransparentECMQVPublicKey",
	KeyFormatTypeTransparentECPrivateKey:    "TransparentECPrivateKey",
	KeyFormatTypeTransparentECPublicKey:     "TransparentECPublicKey",
	KeyFormatTypeTransparentRSAPrivateKey:   "TransparentRSAPrivateKey",
	KeyFormatTypeTransparentRSAPublicKey:    "TransparentRSAPublicKey",
	KeyFormatTypeTransparentSymmetricKey:    "TransparentSymmetricKey",
	KeyFormatTypeX_509:                      "X_509",
}

func (k KeyFormatType) String() string {
	if s, ok := _KeyFormatTypeValueToNameMap[k]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", k)
}

func ParseKeyFormatType(s string) (KeyFormatType, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return KeyFormatType(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _KeyFormatTypeNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v KeyFormatType
		return v, fmt.Errorf("%s is not a valid KeyFormatType", s)
	}
}

func (k KeyFormatType) MarshalText() (text []byte, err error) {
	return []byte(k.String()), nil
}

func (k *KeyFormatType) UnmarshalText(text []byte) (err error) {
	*k, err = ParseKeyFormatType(string(text))
	return
}

func (k KeyFormatType) MarshalTTLVEnum() uint32 {
	return uint32(k)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Object Type Enumeration
// 9.1.3.2.12
type ObjectType uint32

const (
	ObjectTypeCertificate  ObjectType = 0x00000001
	ObjectTypeOpaqueObject ObjectType = 0x00000008
	ObjectTypePGPKey       ObjectType = 0x00000009
	ObjectTypePrivateKey   ObjectType = 0x00000004
	ObjectTypePublicKey    ObjectType = 0x00000003
	ObjectTypeSecretData   ObjectType = 0x00000007
	ObjectTypeSplitKey     ObjectType = 0x00000005
	ObjectTypeSymmetricKey ObjectType = 0x00000002
	ObjectTypeTemplate     ObjectType = 0x00000006
)

var _ObjectTypeNameToValueMap = map[string]ObjectType{
	"Certificate":  ObjectTypeCertificate,
	"OpaqueObject": ObjectTypeOpaqueObject,
	"PGPKey":       ObjectTypePGPKey,
	"PrivateKey":   ObjectTypePrivateKey,
	"PublicKey":    ObjectTypePublicKey,
	"SecretData":   ObjectTypeSecretData,
	"SplitKey":     ObjectTypeSplitKey,
	"SymmetricKey": ObjectTypeSymmetricKey,
	"Template":     ObjectTypeTemplate,
}

var _ObjectTypeValueToNameMap = map[ObjectType]string{
	ObjectTypeCertificate:  "Certificate",
	ObjectTypeOpaqueObject: "OpaqueObject",
	ObjectTypePGPKey:       "PGPKey",
	ObjectTypePrivateKey:   "PrivateKey",
	ObjectTypePublicKey:    "PublicKey",
	ObjectTypeSecretData:   "SecretData",
	ObjectTypeSplitKey:     "SplitKey",
	ObjectTypeSymmetricKey: "SymmetricKey",
	ObjectTypeTemplate:     "Template",
}

func (o ObjectType) String() string {
	if s, ok := _ObjectTypeValueToNameMap[o]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", o)
}

func ParseObjectType(s string) (ObjectType, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return ObjectType(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _ObjectTypeNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v ObjectType
		return v, fmt.Errorf("%s is not a valid ObjectType", s)
	}
}

func (o ObjectType) MarshalText() (text []byte, err error) {
	return []byte(o.String()), nil
}

func (o *ObjectType) UnmarshalText(text []byte) (err error) {
	*o, err = ParseObjectType(string(text))
	return
}

func (o ObjectType) MarshalTTLVEnum() uint32 {
	return uint32(o)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Operation Enumeration
// 9.1.3.2.27
type Operation uint32

const (
	OperationActivate           Operation = 0x00000012
	OperationAddAttribute       Operation = 0x0000000d
	OperationArchive            Operation = 0x00000015
	OperationCancel             Operation = 0x00000019
	OperationCertify            Operation = 0x00000006
	OperationCheck              Operation = 0x00000009
	OperationCreate             Operation = 0x00000001
	OperationCreateKeyPair      Operation = 0x00000002
	OperationCreateSplitKey     Operation = 0x00000028
	OperationDecrypt            Operation = 0x00000020
	OperationDeleteAttribute    Operation = 0x0000000f
	OperationDeriveKey          Operation = 0x00000005
	OperationDestroy            Operation = 0x00000014
	OperationDiscoverVersions   Operation = 0x0000001e
	OperationEncrypt            Operation = 0x0000001f
	OperationExport             Operation = 0x0000002b
	OperationGet                Operation = 0x0000000a
	OperationGetAttributeList   Operation = 0x0000000c
	OperationGetAttributes      Operation = 0x0000000b
	OperationGetUsageAllocation Operation = 0x00000011
	OperationHash               Operation = 0x00000027
	OperationImport             Operation = 0x0000002a
	OperationJoinSplitKey       Operation = 0x00000029
	OperationLocate             Operation = 0x00000008
	OperationMAC                Operation = 0x00000023
	OperationMACVerify          Operation = 0x00000024
	OperationModifyAttribute    Operation = 0x0000000e
	OperationNotify             Operation = 0x0000001b
	OperationObtainLease        Operation = 0x00000010
	OperationPoll               Operation = 0x0000001a
	OperationPut                Operation = 0x0000001c
	OperationQuery              Operation = 0x00000018
	OperationRNGRetrieve        Operation = 0x00000025
	OperationRNGSeed            Operation = 0x00000026
	OperationReCertify          Operation = 0x00000007
	OperationReKey              Operation = 0x00000004
	OperationReKeyKeyPair       Operation = 0x0000001d
	OperationRecover            Operation = 0x00000016
	OperationRegister           Operation = 0x00000003
	OperationRevoke             Operation = 0x00000013
	OperationSign               Operation = 0x00000021
	OperationSignatureVerify    Operation = 0x00000022
	OperationValidate           Operation = 0x00000017
)

var _OperationNameToValueMap = map[string]Operation{
	"Activate":           OperationActivate,
	"AddAttribute":       OperationAddAttribute,
	"Archive":            OperationArchive,
	"Cancel":             OperationCancel,
	"Certify":            OperationCertify,
	"Check":              OperationCheck,
	"Create":             OperationCreate,
	"CreateKeyPair":      OperationCreateKeyPair,
	"CreateSplitKey":     OperationCreateSplitKey,
	"Decrypt":            OperationDecrypt,
	"DeleteAttribute":    OperationDeleteAttribute,
	"DeriveKey":          OperationDeriveKey,
	"Destroy":            OperationDestroy,
	"DiscoverVersions":   OperationDiscoverVersions,
	"Encrypt":            OperationEncrypt,
	"Export":             OperationExport,
	"Get":                OperationGet,
	"GetAttributeList":   OperationGetAttributeList,
	"GetAttributes":      OperationGetAttributes,
	"GetUsageAllocation": OperationGetUsageAllocation,
	"Hash":               OperationHash,
	"Import":             OperationImport,
	"JoinSplitKey":       OperationJoinSplitKey,
	"Locate":             OperationLocate,
	"MAC":                OperationMAC,
	"MACVerify":          OperationMACVerify,
	"ModifyAttribute":    OperationModifyAttribute,
	"Notify":             OperationNotify,
	"ObtainLease":        OperationObtainLease,
	"Poll":               OperationPoll,
	"Put":                OperationPut,
	"Query":              OperationQuery,
	"RNGRetrieve":        OperationRNGRetrieve,
	"RNGSeed":            OperationRNGSeed,
	"ReCertify":          OperationReCertify,
	"ReKey":              OperationReKey,
	"ReKeyKeyPair":       OperationReKeyKeyPair,
	"Recover":            OperationRecover,
	"Register":           OperationRegister,
	"Revoke":             OperationRevoke,
	"Sign":               OperationSign,
	"SignatureVerify":    OperationSignatureVerify,
	"Validate":           OperationValidate,
}

var _OperationValueToNameMap = map[Operation]string{
	OperationActivate:           "Activate",
	OperationAddAttribute:       "AddAttribute",
	OperationArchive:            "Archive",
	OperationCancel:             "Cancel",
	OperationCertify:            "Certify",
	OperationCheck:              "Check",
	OperationCreate:             "Create",
	OperationCreateKeyPair:      "CreateKeyPair",
	OperationCreateSplitKey:     "CreateSplitKey",
	OperationDecrypt:            "Decrypt",
	OperationDeleteAttribute:    "DeleteAttribute",
	OperationDeriveKey:          "DeriveKey",
	OperationDestroy:            "Destroy",
	OperationDiscoverVersions:   "DiscoverVersions",
	OperationEncrypt:            "Encrypt",
	OperationExport:             "Export",
	OperationGet:                "Get",
	OperationGetAttributeList:   "GetAttributeList",
	OperationGetAttributes:      "GetAttributes",
	OperationGetUsageAllocation: "GetUsageAllocation",
	OperationHash:               "Hash",
	OperationImport:             "Import",
	OperationJoinSplitKey:       "JoinSplitKey",
	OperationLocate:             "Locate",
	OperationMAC:                "MAC",
	OperationMACVerify:          "MACVerify",
	OperationModifyAttribute:    "ModifyAttribute",
	OperationNotify:             "Notify",
	OperationObtainLease:        "ObtainLease",
	OperationPoll:               "Poll",
	OperationPut:                "Put",
	OperationQuery:              "Query",
	OperationRNGRetrieve:        "RNGRetrieve",
	OperationRNGSeed:            "RNGSeed",
	OperationReCertify:          "ReCertify",
	OperationReKey:              "ReKey",
	OperationReKeyKeyPair:       "ReKeyKeyPair",
	OperationRecover:            "Recover",
	OperationRegister:           "Register",
	OperationRevoke:             "Revoke",
	OperationSign:               "Sign",
	OperationSignatureVerify:    "SignatureVerify",
	OperationValidate:           "Validate",
}

func (o Operation) String() string {
	if s, ok := _OperationValueToNameMap[o]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", o)
}

func ParseOperation(s string) (Operation, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return Operation(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _OperationNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v Operation
		return v, fmt.Errorf("%s is not a valid Operation", s)
	}
}

func (o Operation) MarshalText() (text []byte, err error) {
	return []byte(o.String()), nil
}

func (o *Operation) UnmarshalText(text []byte) (err error) {
	*o, err = ParseOperation(string(text))
	return
}

func (o Operation) MarshalTTLVEnum() uint32 {
	return uint32(o)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Result Status Enumeration
// 9.1.3.2.28
type ResultStatus uint32

const (
	ResultStatusOperationFailed  ResultStatus = 0x00000001
	ResultStatusOperationPending ResultStatus = 0x00000002
	ResultStatusOperationUndone  ResultStatus = 0x00000003
	ResultStatusSuccess          ResultStatus = 0x00000000
)

var _ResultStatusNameToValueMap = map[string]ResultStatus{
	"OperationFailed":  ResultStatusOperationFailed,
	"OperationPending": ResultStatusOperationPending,
	"OperationUndone":  ResultStatusOperationUndone,
	"Success":          ResultStatusSuccess,
}

var _ResultStatusValueToNameMap = map[ResultStatus]string{
	ResultStatusOperationFailed:  "OperationFailed",
	ResultStatusOperationPending: "OperationPending",
	ResultStatusOperationUndone:  "OperationUndone",
	ResultStatusSuccess:          "Success",
}

func (r ResultStatus) String() string {
	if s, ok := _ResultStatusValueToNameMap[r]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", r)
}

func ParseResultStatus(s string) (ResultStatus, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return ResultStatus(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _ResultStatusNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v ResultStatus
		return v, fmt.Errorf("%s is not a valid ResultStatus", s)
	}
}

func (r ResultStatus) MarshalText() (text []byte, err error) {
	return []byte(r.String()), nil
}

func (r *ResultStatus) UnmarshalText(text []byte) (err error) {
	*r, err = ParseResultStatus(string(text))
	return
}

func (r ResultStatus) MarshalTTLVEnum() uint32 {
	return uint32(r)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Result Reason Enumeration
// 9.1.3.2.29
type ResultReason uint32

const (
	ResultReasonApplicationNamespaceNotSupported ResultReason = 0x0000000f
	ResultReasonAttestationFailed                ResultReason = 0x00000015
	ResultReasonAttestationRequired              ResultReason = 0x00000014
	ResultReasonAuthenticationNotSuccessful      ResultReason = 0x00000003
	ResultReasonCryptographicFailure             ResultReason = 0x0000000a
	ResultReasonEncodingOptionError              ResultReason = 0x00000012
	ResultReasonFeatureNotSupported              ResultReason = 0x00000008
	ResultReasonGeneralFailure                   ResultReason = 0x00000100
	ResultReasonIllegalOperation                 ResultReason = 0x0000000b
	ResultReasonIndexOutOfBounds                 ResultReason = 0x0000000e
	ResultReasonInvalidField                     ResultReason = 0x00000007
	ResultReasonInvalidMessage                   ResultReason = 0x00000004
	ResultReasonItemNotFound                     ResultReason = 0x00000001
	ResultReasonKeyCompressionTypeNotSupported   ResultReason = 0x00000011
	ResultReasonKeyFormatTypeNotSupported        ResultReason = 0x00000010
	ResultReasonKeyValueNotPresent               ResultReason = 0x00000013
	ResultReasonMissingData                      ResultReason = 0x00000006
	ResultReasonNotExtractable                   ResultReason = 0x00000017
	ResultReasonObjectAlreadyExists              ResultReason = 0x00000018
	ResultReasonObjectArchived                   ResultReason = 0x0000000d
	ResultReasonOperationCanceledByRequester     ResultReason = 0x00000009
	ResultReasonOperationNotSupported            ResultReason = 0x00000005
	ResultReasonPermissionDenied                 ResultReason = 0x0000000c
	ResultReasonResponseTooLarge                 ResultReason = 0x00000002
	ResultReasonSensitive                        ResultReason = 0x00000016
)

var _ResultReasonNameToValueMap = map[string]ResultReason{
	"ApplicationNamespaceNotSupported": ResultReasonApplicationNamespaceNotSupported,
	"AttestationFailed":                ResultReasonAttestationFailed,
	"AttestationRequired":              ResultReasonAttestationRequired,
	"AuthenticationNotSuccessful":      ResultReasonAuthenticationNotSuccessful,
	"CryptographicFailure":             ResultReasonCryptographicFailure,
	"EncodingOptionError":              ResultReasonEncodingOptionError,
	"FeatureNotSupported":              ResultReasonFeatureNotSupported,
	"GeneralFailure":                   ResultReasonGeneralFailure,
	"IllegalOperation":                 ResultReasonIllegalOperation,
	"IndexOutOfBounds":                 ResultReasonIndexOutOfBounds,
	"InvalidField":                     ResultReasonInvalidField,
	"InvalidMessage":                   ResultReasonInvalidMessage,
	"ItemNotFound":                     ResultReasonItemNotFound,
	"KeyCompressionTypeNotSupported":   ResultReasonKeyCompressionTypeNotSupported,
	"KeyFormatTypeNotSupported":        ResultReasonKeyFormatTypeNotSupported,
	"KeyValueNotPresent":               ResultReasonKeyValueNotPresent,
	"MissingData":                      ResultReasonMissingData,
	"NotExtractable":                   ResultReasonNotExtractable,
	"ObjectAlreadyExists":              ResultReasonObjectAlreadyExists,
	"ObjectArchived":                   ResultReasonObjectArchived,
	"OperationCanceledByRequester":     ResultReasonOperationCanceledByRequester,
	"OperationNotSupported":            ResultReasonOperationNotSupported,
	"PermissionDenied":                 ResultReasonPermissionDenied,
	"ResponseTooLarge":                 ResultReasonResponseTooLarge,
	"Sensitive":                        ResultReasonSensitive,
}

var _ResultReasonValueToNameMap = map[ResultReason]string{
	ResultReasonApplicationNamespaceNotSupported: "ApplicationNamespaceNotSupported",
	ResultReasonAttestationFailed:                "AttestationFailed",
	ResultReasonAttestationRequired:              "AttestationRequired",
	ResultReasonAuthenticationNotSuccessful:      "AuthenticationNotSuccessful",
	ResultReasonCryptographicFailure:             "CryptographicFailure",
	ResultReasonEncodingOptionError:              "EncodingOptionError",
	ResultReasonFeatureNotSupported:              "FeatureNotSupported",
	ResultReasonGeneralFailure:                   "GeneralFailure",
	ResultReasonIllegalOperation:                 "IllegalOperation",
	ResultReasonIndexOutOfBounds:                 "IndexOutOfBounds",
	ResultReasonInvalidField:                     "InvalidField",
	ResultReasonInvalidMessage:                   "InvalidMessage",
	ResultReasonItemNotFound:                     "ItemNotFound",
	ResultReasonKeyCompressionTypeNotSupported:   "KeyCompressionTypeNotSupported",
	ResultReasonKeyFormatTypeNotSupported:        "KeyFormatTypeNotSupported",
	ResultReasonKeyValueNotPresent:               "KeyValueNotPresent",
	ResultReasonMissingData:                      "MissingData",
	ResultReasonNotExtractable:                   "NotExtractable",
	ResultReasonObjectAlreadyExists:              "ObjectAlreadyExists",
	ResultReasonObjectArchived:                   "ObjectArchived",
	ResultReasonOperationCanceledByRequester:     "OperationCanceledByRequester",
	ResultReasonOperationNotSupported:            "OperationNotSupported",
	ResultReasonPermissionDenied:                 "PermissionDenied",
	ResultReasonResponseTooLarge:                 "ResponseTooLarge",
	ResultReasonSensitive:                        "Sensitive",
}

func (r ResultReason) String() string {
	if s, ok := _ResultReasonValueToNameMap[r]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", r)
}

func ParseResultReason(s string) (ResultReason, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return ResultReason(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _ResultReasonNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v ResultReason
		return v, fmt.Errorf("%s is not a valid ResultReason", s)
	}
}

func (r ResultReason) MarshalText() (text []byte, err error) {
	return []byte(r.String()), nil
}

func (r *ResultReason) UnmarshalText(text []byte) (err error) {
	*r, err = ParseResultReason(string(text))
	return
}

func (r ResultReason) MarshalTTLVEnum() uint32 {
	return uint32(r)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Batch Error Continuation Enumeration
// 9.1.3.2.30
type BatchErrorContinuation uint32

const (
	BatchErrorContinuationContinue BatchErrorContinuation = 0x00000001
	BatchErrorContinuationStop     BatchErrorContinuation = 0x00000002
	BatchErrorContinuationUndo     BatchErrorContinuation = 0x00000003
)

var _BatchErrorContinuationNameToValueMap = map[string]BatchErrorContinuation{
	"Continue": BatchErrorContinuationContinue,
	"Stop":     BatchErrorContinuationStop,
	"Undo":     BatchErrorContinuationUndo,
}

var _BatchErrorContinuationValueToNameMap = map[BatchErrorContinuation]string{
	BatchErrorContinuationContinue: "Continue",
	BatchErrorContinuationStop:     "Stop",
	BatchErrorContinuationUndo:     "Undo",
}

func (b BatchErrorContinuation) String() string {
	if s, ok := _BatchErrorContinuationValueToNameMap[b]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", b)
}

func ParseBatchErrorContinuation(s string) (BatchErrorContinuation, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return BatchErrorContinuation(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _BatchErrorContinuationNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v BatchErrorContinuation
		return v, fmt.Errorf("%s is not a valid BatchErrorContinuation", s)
	}
}

func (b BatchErrorContinuation) MarshalText() (text []byte, err error) {
	return []byte(b.String()), nil
}

func (b *BatchErrorContinuation) UnmarshalText(text []byte) (err error) {
	*b, err = ParseBatchErrorContinuation(string(text))
	return
}

func (b BatchErrorContinuation) MarshalTTLVEnum() uint32 {
	return uint32(b)
} // Code generated by "kmipenums "; DO NOT EDIT.

// Attestation Type Enumeration
// 9.1.3.2.36
type AttestationType uint32

const (
	AttestationTypeSAMLAssertion      AttestationType = 0x00000003
	AttestationTypeTCGIntegrityReport AttestationType = 0x00000002
	AttestationTypeTPMQuote           AttestationType = 0x00000001
)

var _AttestationTypeNameToValueMap = map[string]AttestationType{
	"SAMLAssertion":      AttestationTypeSAMLAssertion,
	"TCGIntegrityReport": AttestationTypeTCGIntegrityReport,
	"TPMQuote":           AttestationTypeTPMQuote,
}

var _AttestationTypeValueToNameMap = map[AttestationType]string{
	AttestationTypeSAMLAssertion:      "SAMLAssertion",
	AttestationTypeTCGIntegrityReport: "TCGIntegrityReport",
	AttestationTypeTPMQuote:           "TPMQuote",
}

func (a AttestationType) String() string {
	if s, ok := _AttestationTypeValueToNameMap[a]; ok {
		return s
	}
	return fmt.Sprintf("%#08x", a)
}

func ParseAttestationType(s string) (AttestationType, error) {
	if strings.HasPrefix(s, "0x") && len(s) == 10 {
		b, err := hex.DecodeString(s[2:])
		if err != nil {
			return 0, err
		}
		return AttestationType(binary.BigEndian.Uint32(b)), nil
	}
	if v, ok := _AttestationTypeNameToValueMap[s]; ok {
		return v, nil
	} else {
		var v AttestationType
		return v, fmt.Errorf("%s is not a valid AttestationType", s)
	}
}

func (a AttestationType) MarshalText() (text []byte, err error) {
	return []byte(a.String()), nil
}

func (a *AttestationType) UnmarshalText(text []byte) (err error) {
	*a, err = ParseAttestationType(string(text))
	return
}

func (a AttestationType) MarshalTTLVEnum() uint32 {
	return uint32(a)
}
